### ISSUE TITLE
FatalErrorException in HasTranslations.php line 31:

### ISSUE THREAD

**Issue by reina3596** [spatie/laravel-translatable#10]
Hello guys,

I encountered this error.

"Default value for parameters with a class type hint can only be NULL"

I have seen in Code, that this line appears in red, just where I found the error.

Any ideas???

Thanks and Good Job¡¡¡

**Comment by sebastiandedeyne** [comment]
What PHP version are you on? This package requires v7.0+.

If you're on 7 or above, could you post the exact line that throws an error?

**Comment by reina3596** [comment]
Its oks.

Issue solved¡¡¡ Php Updated

Thankssssss

**Comment by amrkhaled44** [comment]
I can't update php v. in my Cpanel ?
