### ISSUE TITLE
Saving characters with the proper json unicode

### ISSUE THREAD

**Issue by majebry** [spatie/laravel-translatable#103]
Hello

When checking saved data for arabic language I see characters look like this:
![screen shot 2018-01-02 at 12 22 53 pm](https://user-images.githubusercontent.com/7958772/34481053-8cd36efe-efb8-11e7-9354-75a14165e482.png)
While this is the actual inputs:
![screen shot 2018-01-02 at 12 25 58 pm](https://user-images.githubusercontent.com/7958772/34481029-6eb0a842-efb8-11e7-852c-298eecff524b.png)

Any ideas how to improve it?

**Comment by fahjan** [comment]
hi spatie, you can use

**Comment by fahjan** [comment]
JSON_UNESCAPED_UNICODE
json_encode('بسم الله', JSON_UNESCAPED_UNICODE);

**Comment by fahjan** [comment]
Hi spatie, you can use JSON_UNESCAPED_UNICODE in json_encode 
json_encode('بسم الله', JSON_UNESCAPED_UNICODE);

https://stackoverflow.com/questions/14980421/arabic-characters-in-json-decoding

**Comment by fahjan** [comment]
I need this for **searching** and sorting

**Comment by freekmurze** [comment]
Feel free to PR this with tests.

**Comment by hamidlahouiri** [comment]
hello, I need  a solution for arabic search with local scope scope
my code is :
 public function scopeSearch($query, $s) {
    	return $query->where('code', 'like', '%'.$s.'%')
                ->orWhere('name', 'like', '%'.$s.'%');  			
    }
I need to search translate name in arabic.

**Comment by omartawba1** [comment]
@majebry I know it's really a late reply but you could paste this code snippet in your model till I'll make PR for this!

    ```
    /**
     * Encode the given value as JSON.
     *
     * @param  mixed  $value
     * @return string
     */
    protected function asJson($value)
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }
```

**Comment by Pefren** [comment]
@omartawba1 still no updates?

**Comment by omartawba1** [comment]
@Pefren At that time, I found that this method `asJson` doesn't belong to `spatie/laravel-translatable` and belongs to one of the Laravel packages, and my PR wouldn't be accepted because some other languages need to `ESCAPED_UNICODE`.

So, the fastest solution for me at that point was to just overwrite the method inside the model.

**Comment by Saifallak** [comment]
following @omartawba1 suggestion i made a trait

```php
<?php

namespace App\Traits;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

trait EscapeUniCodeJson
{
    /**
     * Encode the given value as JSON.
     *
     * @param  mixed  $value
     * @return string
     */
    protected function asJson($value): string
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }
}

```

and then i use it inside any model that uses spatie translatable

**Comment by mrtawil** [comment]
Hello @freekmurze, I am still having the same issue till today. Isn't this fix merged into the main repo as you have mentioned doing previously? I see that the PR was closed without a merge.

It would be very nice from you to merge the fix soon so we all can benefit from it.

**Comment by Saifallak** [comment]
> Hello @freekmurze, I am still having the same issue till today. Isn't this fix merged into the main repo as you have mentioned doing previously? I see that the PR was closed without a merge.
> 
> It would be very nice from you to merge the fix soon so we all can benefit from it.

Per https://github.com/spatie/laravel-translatable/issues/103#issuecomment-864462662 .. asJson function doesn't belong to spatie package at all
