### ISSUE TITLE
How to migrate an existing model where we don't have any translation set

### ISSUE THREAD

**Issue by lmartins** [spatie/laravel-translatable#111]
I'm am trying to apply this package to a project where we already have many entries on the database.
My plan was to set the model as translatable using the Trait and appropriate configuration, then write a database migration that would go through each post and set the current "raw" value as the default language (English in this case). 

This is that when on the frontend we see these models.

Problem is to write a migration, I would need to retrieve those default raw values, so I could then use the translatable methods to set those values as the default translation.

However, from the moment model is set to use the translatable trait, pulling any translatable property returns an empty string.

```php
>>> $prod = Product::find(2);
=> App\Product {#1080
     id: 2,
     name: "Product Title",
     description: "Product Description",
     status: 1,
     created_at: "2017-12-20 18:38:04",
     updated_at: "2017-12-22 16:31:30",
   }
>>> $prod->name
=> ""
```

Any way to get around this or does this needs to happen with raw MySQL for the first query?

**Comment by lmartins** [comment]
What I ended up doing was basically making a standard MySQL query to get the raw data, loop through each model, convert it to a Eloquent model, then use the raw values to set the default translations.


```php
    $product = DB::table('products')->get();

    foreach ($products as $key => $product) {
      $product = Product::find($product->id);
      $product
        ->setTranslation('name', 'en', $products[$key]->name)
        ->save();
    }
```

Probably there's a better way to do this but this is working for now. 

Thanks.

**Comment by AmooAti** [comment]
Thanks to @lmartins 

I came up with another solution due to the size of the data and the PHP execution time limit using MySql query:

```sql
UPDATE products
SET name = JSON_SET('{}', '$.en', name);
```

**Comment by RJ2020DD** [comment]
Just sharing in case this helps someone. I created a console command to run the following:

```PHP
DB::table('products')->update([
    'name' => DB::raw("JSON_SET('{}', '$.en', name)"),
]);
```
