### ISSUE TITLE
Validate Translatable Attribute

### ISSUE THREAD

**Issue by StanBarrows** [spatie/laravel-translatable#112]
Let's assume I have a translatable '**Name**' attribute for several languages. Now I would like to implement a simple Validation for new models.

```
public function rules()
    {
        return [
            'name' => 'required|string|max:255|unique:models,name',
        ];
    }

```

Any ideas on how to validate the existing translations? Or how a custom validation Rule could look like?

Cheers, Stan

**Comment by angeloo** [comment]
You can do something like that:

`
public function rules()
{

$rules = [
    'price' => 'required',
];

$trules = []; // 
foreach (Localization::locales() as $locale) {
    $trules = $trules + [
        Localization::translate_field_name('name', $locale) => 'required|string',
    ];
}

return $rules + $trules;

}
`

helper somewhere....
`
static function locales(): Collection
    {
        return collect(config('app.locales'));
    }
`

config/app.php
`
'locales' => ['de', 'en', 'fr'],
`
