### ISSUE TITLE
This database engine does not support JSON operations.

### ISSUE THREAD

**Issue by cubiczx** [spatie/laravel-translatable#113]
This database engine does not support JSON operations.
With Server version: 8.0.12 MySQL Community Server - GPL and Ubuntu 16.04

**Comment by freekmurze** [comment]
Please use a database that supports JSON operations.

**Comment by cubiczx** [comment]
MySQL 5.7 or above for example 8.0.12 the last version of MySQL supports JSON operations, my mistake has been when using SQLITE in my phpunit.xml, i change to MySQL and works fine.
