### ISSUE TITLE
Allow non-translation in table cell

### ISSUE THREAD

**Issue by screenager** [spatie/laravel-translatable#114]
In some models, such as in my case a settings table, it would be useful if you could also store a non translated value in a translatable column. Without the json structure with language keys around the value.

For example, numeric values or foreign keys to language independent objects.

But maybe this question is out of scope, and should we only use the package for properties that represent text..

**Comment by freekmurze** [comment]
This is indeed out of scope. The package is meant for translatable values. If you don't need a translation of a value, just add a property on your model.

**Comment by esameisa** [comment]
did you solve it ? @screenager
