### ISSUE TITLE
Genitive and Accusative

### ISSUE THREAD

**Issue by robjbrain** [spatie/laravel-translatable#116]
Is there anyway to have multiple translations for a specific field, such as Genitive and Accusative? Or in Greek and Finnish there are multiple adjectives for what is just one word in English? Even male and female such as in French?

I looked at possibly having "fr_fe" or "gr1", "gr2" but it all looks like it would become very messy very quickly.

Is it something the package is able to handle or is likely to handle in the future?

**Comment by freekmurze** [comment]
No, we aren't planning to add grammatical rules to this package.
