### ISSUE TITLE
Get in JSON translated keys, only when you ask for them.

### ISSUE THREAD

**Issue by JexPY** [spatie/laravel-translatable#118]
`  

    public function toArray()
    {

        $attributes = parent::toArray();

        foreach ($this->getTranslatableAttributes() as $name) {
            in_array($name, array_keys($attributes), true) ?
            $attributes[$name] = $this->getTranslation($name, app()->getLocale()) :
            '';
        }

        return $attributes;
}

`

Without checking, it was adding translatable keys with no value, when keys were not selected from eloquent query.

**Comment by freekmurze** [comment]
I don't understand the question. Could you submit a failing PR for us to look at?
