### ISSUE TITLE
How to query translatable attributes in postgres?

### ISSUE THREAD

**Issue by semsphy** [spatie/laravel-translatable#12]
Hello Freek,

```php
NewsItem::where('name->en', 'Name in English')->get();
//OR
NewsItem::whereRaw('name->"$.en" = \'Name in English\'')->get();
```

Thanks,

**Comment by freekmurze** [comment]
Hi,

I don't know use Postgres myself 😁 

So, experiment with it a bit and let me know what's the best way to do this...

**Comment by aeq-dev** [comment]
Hello here,
I have same issue here, @semsphy did you find a solution please ?
