### ISSUE TITLE
Type error: Return value of App\Config::getTranslations() must be of the type array

### ISSUE THREAD

**Issue by ahmedash95** [spatie/laravel-translatable#13]
At first thanks for this awesome package. my case is i have a config table with [ key , value ] columns, the value might be contain text that i need to be translatable and might contain file path like logo.png path. do you have solution for this case ?

**Comment by freekmurze** [comment]
I don't know if I understand your question correctly. If a field is marked as translatable all records will hold a json for field. There are no exceptions.

If I misinterpreted your questions, please show me some code / data.

**Comment by ahmedash95** [comment]
@freekmurze ok, let me explain more ... i mean that the field might be translatable for some rows and may be not for other like 

| key  | value |
| --- | --- |
| site_name | { en : Ahmed , ar : احمد } |
| site_logo | uploads/image/logo |


now if i tried to get the value of the second row will return exception HasTranslations expect value to be an array not string

**Comment by freekmurze** [comment]
Thanks for clarifying your question. This package does not support the behaviour you're asking for. I believe most users of this package are not using the package in this way, so I probably won't add the functionality (or accept a PR for this)

You're of course free to fork to package an customise it to your liking.

**Comment by ahmedash95** [comment]
i know it's some kind weird behavior .. at all thanks for your replays :)
