### ISSUE TITLE
Add support for JSON_UNESCAPED_UNICODE

### ISSUE THREAD

**Issue by MicroDroid** [spatie/laravel-translatable#134]
Currently, things get stored in my DB like this:

```JSON
{"a":"\u00e1"}
```

but I want it like this:

```JSON
{"a":"á"}
```

This is because I want to do a search in MySQL using the `LIKE` query and using the `\d` notation breaks it.

See [this](https://stackoverflow.com/questions/6771938/any-way-to-return-php-json-encode-with-encode-utf-8-and-not-unicode)

**Comment by freekmurze** [comment]
I'm thinking this should be fixed at the Laravel level. Open up an issue there.
