### ISSUE TITLE
Sorted json?

### ISSUE THREAD

**Issue by robov** [spatie/laravel-translatable#140]
When I have 3 languages (defined in this order)
`En ,  Nl , De`
Then the json in the database holds the data sorted
as in : 
`de , en, nl`

How can I turn off this sorting, I want the structure in the database to match the order of my languages

**Comment by freekmurze** [comment]
For our projects the sorting of the fields in the db is not important. That's why there is no code at all to make the languages to be stored in a certain order.

If you need this, PR it. I'll consider merging it in if the code is simple and well tested.

**Comment by robov** [comment]
Thanks, it seems that the code is somehow sorting the keys alphabetically, I just need to figuure out where this sorting happens in your package
p.s. thanks for this package.. it is really superb

**Comment by esameisa** [comment]
@robov how do you change website language with 
`App::setLocale($language);`
or what?
and where you write it ?
