### ISSUE TITLE
Querying translatable attributes didn't work with me ??

### ISSUE THREAD

**Issue by esameisa** [spatie/laravel-translatable#141]
i try to write
$products = Products::where('name->en', 'Mobile')->get();

but i found this error:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."ar"' = ?' at line 1

**Comment by freekmurze** [comment]
This package does not support MariaDB, please use MySQL.

**Comment by abuoop** [comment]
could you have plan in future to implemented on MariaDB ? or what
