### ISSUE TITLE
how can i change language ?

### ISSUE THREAD

**Issue by esameisa** [spatie/laravel-translatable#142]
when i try to write:
`App::setLocale('ar');
`
then go to any page i found it return to 'en'

why? 

**edit:**
i try to write this in middleware but i asked for another way?
`$language = $request->session()->has('language') ? \Session::get('language') : 'en';
\App::setLocale($language);
\Session::put('language', $language);`

**Comment by freekmurze** [comment]
`setLocale` only changes the locale for the current request. If you need to change for multiple requests use sessions. You could also add locale to the url eg. `https://yoursite.com/en/page` and set the locale according to the value in the url.
