### ISSUE TITLE
Having "0" as translation value will be discarded

### ISSUE THREAD

**Issue by robinmartini** [spatie/laravel-translatable#143]
Hey,

If I have a zero as a translation for one of my models and that value is not returned properly when retrieving.

Example model:
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Item extends Model
{
    use HasTranslations;

    public $translatable = ['code'];
}
```

Storing a code in two locales:
```
$item = new Item();
$item->setTranslation('code', 'en', '1');
$item->setTranslation('code', 'nl', '0');
$item->save();
```

In the database the values are store correctly:
`{"en": "1", "nl": "0"}`

However, when retrieving the value for the dutch translation I get an empty response:
```
$item->getTranslation('code', 'nl'); // returns an empty string i.s.o. 0
```

Is there any way to circumvent this?

Thank you in advance.

**Comment by freekmurze** [comment]
I'm thinking this should just work. Could you PR a failing test for me to look at?

**Comment by robinmartini** [comment]
Thank you for the quick response.

I have added a PR that includes tests to illustrate the issue and I was able to find the cause and a fix is added to the PR as well.

**Comment by freekmurze** [comment]
A new release that includes your PR has been tagged. Thank you!
