### ISSUE TITLE
Does this project offer full locale support? like 'fr_CA' (french Canada) vs just purely 'fr'

### ISSUE THREAD

**Issue by armyofda12mnkeys** [spatie/laravel-translatable#145]
Hey spatie, had a few questions if thats alright:

1. Does this project offer full locale support? 
like if you wanted separate translations for 'fr_CA' (french Canada) and 'fr_FR' (french France) vs just purely 'fr' (french).

2. Also if those types of locales are supported... another question... 
I see there is a default fallback fallback_locale for a fallback, pretend its usually set to 'en'. 
But if the 'fr_BE' (french Belgium) translation isn't found, lets say I don't want to immediately pull the 'en' fallback, but 1st try and see if a 'general language' translation was found, aka a translation purely for 'fr'.
Is that possible, or need some custom code to handle that?

3. if full locales are supported... So when trying to create a UI to translate our models, pretend there will be a dropdown which allows you to multi-select generic language(s), or locale lang-Country combos in a dropdown list like: [english (en), english-United States (en-US), french (fr), french Canada (fr-CA), french France (fr-FR), spanish (es), spanish Mexico (es-MX), spanish Spain (es-ES)]. 
Lets say a user originally selected 'french(fr)' AND 'french Canada (fr-CA)', 
  and now deletes 'french Canada (fr-CA)', and adds 'french France (fr-FR)' and then clicks Save on the page.
Is there a nice method to basically handle saving 'french(fr)' and 'french France (fr-FR)', 
Like can you use: 
```
$newsItem->setTranslations('title', [
   'fr' => 'Title in generic french'
   'fr-FR' => 'Title in french France!'
];)
```
and will it automatically delete the fr-CA one i wanted deleted earlier.
or do I need to call forgetTranslation('title', 'fr-CA') 1st, before calling that?

4. I guess this is more of a suggestion as I don't see in documentation.
Would be cool to have ability to associate multiple locales with one translation, vs putting the same translation multiple times for each lang.
Like in my UI, you can pick which locales to associate to this translation:
https://farm5.staticflickr.com/4895/31633910997_3f8530af8c_o.png
and the code can do something like this:

```
$newsItem->setTranslationsMultipleFields([
  [
    'field'=>'title',
    'locales'=>['fr', 'fr-FR', 'fr-CA'], 
    'translation'=>'Generic Title field:'
  ],
  [
    'field'=>'body',
    'locales'=>['fr', 'fr-FR', 'fr-CA'], 
    'translation'=>'Generic Body field:'
  ],
  [ //one to many relationship, is this handled?
    'field'=>'article_pics',
    'locales'=>['fr', 'fr-FR', 'fr-CA'], 
    'translation'=>['path/french-1.jpg', 'path/french-2.jpg', 'path/french-3.jpg']
  ],
]);

```
Not sure if it seems useful, but just thought I'd mention.

This brings me to one last question:
5. Does this project support 1:Many translations for a model? like my NewsItem model has an articlepics association which is associated with a 1:Many relationship (multiple pics allowed per NewsItem translation). Can you pass an array of pics (aka an array of string file location paths) to the attribute's translatable value? 
I don't really see an example of how to do this in the docs. Pretend this is the model for example:

```
class NewsItem extends Model
{
    use HasTranslations; 
    public $translatable = ['title', 'body', 'articlepics???'];
    public function articlepics()
    {
        return $this->hasMany('App\ArticlePics');
    }
}

```
Then set the relation's translations with:
`$newsItem->setTranslation('articlepics', 'fr-CA', ['path/french-1.jpg', 'path/french-2.jpg', 'path/french-3.jpg']
`
Sorry for soooo many questions. 
You can answer whenever as I'm just curious about this project but not using yet for a few weeks,
Thanks!,
Ari

**Comment by freekmurze** [comment]
1. You can use whatever string you want as a locale
2. You probably need custom code for that
3. The question isn't 100% clear to me, I suggest you just try it out. 
4. We didn't need that use case in our project, so it isn't supported in this package
5. That's also not supported. This is a really simple package for just the "easy" use cases.
