### ISSUE TITLE
Determine Languages?

### ISSUE THREAD

**Issue by zymawy** [spatie/laravel-translatable#146]
Nice Package As Always, **Spatie**. 

I Needed To Determine How Many Languages Are Saved On In Every Model!.
I Want To It To Make A Dynamic Inputs Feilds When Someone Editing The Content Of Specific Content.
So It Maybe More Than Languages. 

So That I Can Loop Throw All Language And Make Input For It?

**Comment by freekmurze** [comment]
The translations are store in your model as json. Just add a method on your model to count the languages or get the used languages out of the saved json.
