### ISSUE TITLE
Translated slugs and indexing

### ISSUE THREAD

**Issue by Achrafml23** [spatie/laravel-translatable#147]
I used this package with "cviebrock/eloquent-sluggable" and it worked like a charm!

The problem is that binding the slug from json column is not advised at all !
(Route Model Binding defined in the RouteServiceProvider somthing like:
` "Post::where('slug->en', 'slug-in-english')->first(); "` ).
Because the column has to be an indexed column! So i don't know if i have to generate indexed columns from the json column or create as many indexes as the languages!

Any help or suggestions ?!
Thank you.
Any thoughts @freekmurze ?Thank you!

**Comment by sanneterpstra** [comment]
@Achrafml23 Did you solve this problem? If so, could you please share the solution you implemented?

**Comment by Achrafml23** [comment]
No, i just left slugs in only one language! I had no time to dig any deeper :/ .
