### ISSUE TITLE
It doesn't support UTF8.

### ISSUE THREAD

**Issue by semsphy** [spatie/laravel-translatable#16]
```php
$item->setTranslations('description',['en' => 'Hello', 'kh' => 'សួរស្តី']);
```

I got this TypeError: Return value of  **getTranslations()** must be of the type array, string returned.

Thanks,

**Comment by sebastiandedeyne** [comment]
What does the json look like that gets stored in the database fiedl?

**Comment by freekmurze** [comment]
The tests seem to point out that [UTF8 is not the problem](https://github.com/spatie/laravel-translatable/blob/e1202ed/tests/TranslatableTest.php#L175-L182) here.
