### ISSUE TITLE
Install problem TranslatableServiceProvider not found

### ISSUE THREAD

**Issue by OrelSBinoklem** [spatie/laravel-translatable#160]
http://prntscr.com/n62y29

**Comment by freekmurze** [comment]
The tests seem fine. I can install it without any problems in a fresh laravel app.

**Comment by rico** [comment]
@freekmurze I have the same problem. It is there in the `composer.json`: 

    "extra": {
        "laravel": {
            "providers": [
                "Spatie\\Translatable\\TranslatableServiceProvider"
            ]
        }
    }

But can't find the class it in the source:

![image](https://user-images.githubusercontent.com/92818/55504242-bb39a380-5650-11e9-99fe-3ea0425001b6.png)

I tried to install `4.0.0`.

Thank you for having a look at it.

**Comment by rico** [comment]
@OrelSBinoklem you can use my fork, where it's fixed. Just add

    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/smartcode-ch/laravel-translatable.git"
        }
    ],

to `composer.json`. Once it is fixed here, you can remove that part and you are back using the original package.

**Comment by aurawindsurfing** [comment]
Looks like it was changed in 4.0.0 downgrade to 3.1.3 and it will work.

**Comment by denjaland** [comment]
Hi,

Just upgraded from 2.2 (yes, I know...) to 4.1.1, and have the same issue...  It's supposedly fixed in 4.1.1, but apparently wasn't, as I'm getting this error now when running my tests...

    1) CheckmailEndpointTest::test_checkmail_endpoint_for_known_user_email
    Error: Class 'Spatie\Translatable\TranslatableServiceProvider' not found

Any idea?

**Comment by whthT** [comment]
Packagist must be update

**Comment by KnowledgeWanderer** [comment]
> The tests seem fine. I can install it without any problems in a fresh laravel app.

What a joke. We can't.

**Comment by stefanocurnis** [comment]
I also have this problem with version 4.
I think it's because I'm on PHP 7.1
Version 4 is now 7.2+.

`laravel new testspatie; cd testspatie; composer require spatie/laravel-translatable`

`> @php artisan package:discover --ansi

In ProviderRepository.php line 208:
                                                                     
  Class 'Spatie\Translatable\TranslatableServiceProvider' not found  `

**Comment by fredsvanelli** [comment]
Can't install here. PHP 7.1.30

![Captura de Tela 2019-07-01 às 11 33 35](https://user-images.githubusercontent.com/10292175/60444949-94a9eb00-9bf4-11e9-9574-8b0f99006f1a.png)

**Comment by janisbarons** [comment]
any solutions?

**Comment by stefanocurnis** [comment]
Use version 3. Version 4 now requires PHP 7.2

**Comment by dev-abstract** [comment]
Add `"spatie/laravel-translatable": "^4.1"` to composer and run `composer update`, the issue doesn't exist there anymore but it requires PHP 7.2
