### ISSUE TITLE
Select many items with relations in a specific language

### ISSUE THREAD

**Issue by hatimox** [spatie/laravel-translatable#162]
hello 

i'm working on a Multi language API , and i was wondering if i can get a list of object with all relations translated based on the default local.

For example i have a Article Model that has many comments so what i want is to get all Articles with their comment translated to the selected language without looping on all items to set the translation manually . 

thanks

**Comment by Grunkhead** [comment]
I don't know if this is exactly what you want. But you can add the locale to your route. So if you navigate to a specific route where the locale is prefixed in. You can get a specific translation. This way you can just use Laravel regular routing system to fetch data.
