### ISSUE TITLE
orderBy with translatable field

### ISSUE THREAD

**Issue by Zlob** [spatie/laravel-translatable#166]
Hi! Thanks for your package, its really helpful!

In my project it is common task to sort entities by translatable field, and i would like to do it via db query. For this purpose I add a macros to `Illuminate\Database\Eloquent\Builder`:
```php
Builder::macro('orderBy', function ($field, $order = 'asc', $locale = null) {
    if (
        in_array(HasTranslations::class, class_uses($this->model))
        && in_array($field, $this->model->translatable)
    ) {
        $locale = $locale ?? app()->getLocale();
        $this->query->orderByRaw("$field->>'$locale' $order");
    } else {
        $this->query->orderBy($field, $order);
    }
    return $this;
});
```
So I can simply call: `Entity::orderBy('name', 'desc', 'en')->get()` to get entities ordered by name in English.

How do you think, should I create a PR with this macros? It can be helpfull not only for me, but it will not work with 'text' translatable fields and it lead to changes in existing tests (rewrite column types in TestModel from `text` to `json`).

**Comment by freekmurze** [comment]
We don't have a need for this functionality, so probably we won't accept a PR for this.

**Comment by superbiche** [comment]
@freekmurze actually this creates a regression in the sense the framework's `orderBy` works but not on translatable fields. There should at least be a warning logged.

Moreover, I find it unusual that an open source project doesn't accept a PR that adds a functionality that's already present in Laravel, just making it available for the fields for which _you_ are changing the behaviors, thus breaking the `orderBy` functionality. 

If this project should only accept PRs that match your needs, there should be at the very least a disclaimer to inform users of this policy. Even if this is quite a strange policy, that will probably lead to forks instead of making the original project more robust.

**Comment by ctf0** [comment]
@Zlob solution wasnt working for some reason so with some changes its finally working now
```php
Builder::macro('orderBy', function ($field, $order = 'asc', $locale = null) {
    if (
        method_exists($this->model, 'getTranslations')
        && in_array($field, $this->model->translatable)
    ) {
        $locale = $locale ?? app()->getLocale();
        $this->query->orderByRaw("$field->'$.$locale' $order");
    } else {
        $this->query->orderBy($field, $order);
    }

    return $this;
});
```

**Comment by Zlob** [comment]
@ctf0 that's because json syntaxis is different in postgresql and mysql.

**Comment by jberculo** [comment]
For people still ending up on this page, you can now use the default laravel syntax for json fields:
`->orderBy('fieldname->key')`
so in this case:
`->orderBy('name->en')`

**Comment by marcomessa** [comment]
I was looking for the same feature and found this thread. Thank you for sharing, but isn't it the same as using core eloquent orderBy?

```
Entity::orderBy('translatableField->lang')
```

In my case I was able to do this:

```
$lang = app()->getLocale();
        
        return [
            'roles' => InterpreterRole::orderBy("name->$lang")->get(),
        ];
```

**Comment by ctf0** [comment]
@marcomessa its the same but instead u can use `orderBy('name')` and the macro will take care of figuring out if we need to add the `->$lang` or not.

**Comment by theChaosCoder** [comment]
@matej-1234 Can you show your error msg?
I had problems too with : `$this->query->orderByRaw("$field->'$.$locale' $order");`

Instead I'm using this now: `$this->query->orderByRaw("JSON_VALUE($field, '$.$locale') $order");`

Not sure why ->$value is not working (I'm using MaraiDB 10.6.5). Guess it still does not support arrow function...

**Comment by 3adeling** [comment]
the update macro

```
Builder::macro('orderBy', function ($field, $order = 'asc', $locale = null) {
            if (
                in_array(HasTranslations::class, class_uses($this->model))
                && in_array($field, $this->model->translatable)
            ) {
                $locale = $locale ?? app()->getLocale();
                $this->query->orderByRaw("$field->\"$.{$locale}\" $order");
            } else {
                $this->query->orderBy($field, $order);
            }
            return $this;
        });
```
