### ISSUE TITLE
Problems with the method create

### ISSUE THREAD

**Issue by alfongoma** [spatie/laravel-translatable#168]
I have a problem with the method create. If I write this 

NewsItem::create([
   'name' => [
      'en' => 'Name in English',
      'nl' => 'Naam in het Nederlands'
   ],
]);

The name is empty, in the database the content is [].

If I write NewsItem::create(['name' =>  'Name in English']); the value of the field is correct   {"en": "Name in English"}

What am I doing wrong?

Thanks in advance

**Comment by freekmurze** [comment]
Try using the setTranslations function mentioned in the readme.
