### ISSUE TITLE
Revert PR 148?

### ISSUE THREAD

**Issue by royduin** [spatie/laravel-translatable#170]
Since https://github.com/spatie/laravel-translatable/pull/148 `app.fallback_locale` is used instead of a package specific config file: `translatable.fallback_locale`. But; we develop our applications in English and based on the customer we set the locale. So with a Dutch customer we have:

- `app.locale`: `nl`
- `app.fallback_locale`: `en`

And they translate everything from English to Dutch with the translation manager from Barry.

But in the customer backend they've an entity which is translatable; for example products. Because it's a Dutch application they give all products a Dutch title and some products an English title in case the product is in an English store. In this case the fallback should be the inverse. So when the locale is set to English and there is no translation the Dutch title should be displayed. Previously `translatable.fallback_locale` was set to `nl` but now we can't do that anymore.

Thoughts? Would a PR to revert this be accepted? @ankurk91 and @freekmurze.

**Comment by freekmurze** [comment]
Ok, send a PR with updated tests that reverts this. Also include a note on why we revert this in the changelog 👍

**Comment by royduin** [comment]
Done, when the config file is published `translatable.fallback_locale` will be used. If not; `app.fallback_locale` is used.

**Comment by freekmurze** [comment]
Thanks!

**Comment by royduin** [comment]
Thank you 😎
