### ISSUE TITLE
adding locale to wheres on runtime

### ISSUE THREAD

**Issue by mojtabaRKS** [spatie/laravel-translatable#180]
it would be very nice if developer not have to modify all their queries and base code from scratch

this patch will add a global scope to all translatable models
to modify their queries on runtime for sake of fast developing ! :)

any advice would be appreciated !

here i created a new pull request and made my changes !
[https://github.com/spatie/laravel-translatable/pull/179](url)
also you can check the code base in  repo in my profile ! :)

**Comment by freekmurze** [comment]
We'll continue this in #179
