### ISSUE TITLE
Translatable and Nova Search

### ISSUE THREAD

**Issue by gldrenthe89** [spatie/laravel-translatable#184]
we use translatable since a week now combined with the power of Nova as a backend. 
The default search in Nova is case insensitive but when installed translatable and set everything up in our models etc. the translatable columns are suddenly only searchable in case sensitive.

Can you pleade make this a option or fix this issue combined with Nova?

**Comment by gldrenthe89** [comment]
As this is related to MySQL and JSON columns wich are case sensitive this can't be resolved within the package. Whe resolved this with making a searchable_name column wich the main translation inside it. using observers this is filled correctly.

Closing this

**Comment by Milkhan** [comment]
> searchable_name

@gldrenthe89 Can you explain it more, please?

**Comment by gldrenthe89** [comment]
> > searchable_name
> 
> @gldrenthe89 Can you explain it more, please?

The main language we use is Dutch, so i have made a additional column on the model wich is filled trough a observer action

`
if($product->isDirty('name') && $product->name != $product->searchable_name) {
            $product->setAttribute('searchable_name', $product->name);
            $product->save();
        }
`

Whe then set the Nova resource setting:

`
public static $search = [
        'id', 'searchable_name'
    ];
`

This allowed us to stil use translations on the front end. Within Nova al translations a editable. The searchable_name column is only used for searching, this column is not editable in Nova.

**Comment by Milkhan** [comment]
@gldrenthe89 Thank you!

**Comment by gldrenthe89** [comment]
> @gldrenthe89 Thank you!

No problem 😉
