### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by furkangiray** [spatie/laravel-translatable#192]
Hi, first of all thanks for this great package but I have a problem about Turkish characters. Normally my database saving my text data without any problem. My translatable columns has problem so how can I solve that ?

**Comment by VeeeneX** [comment]
Can you show any examples? :)

**Comment by furkangiray** [comment]
![image](https://user-images.githubusercontent.com/31952440/76682187-0b640880-660b-11ea-909e-a0be0d598376.png)

Actually it's not a problem in my frontend'pages but you know it's about obsession :)

**Comment by VeeeneX** [comment]
Ok :smiley: so it can be closed?
