### ISSUE TITLE
null value in translation is returned as empty string

### ISSUE THREAD

**Issue by dennisbruinen** [spatie/laravel-translatable#195]
For example, if I have this database value:
`title: "{"nl":null}"`
and I try to get this value from the model, like
`$project->title`
I get an empty string `''` returned instead of `null`. 

This is confusing for me because Laravel returns model values that are not set as `null`, instead of an empty string.

Is there a specific reason an empty string is returned when the value is `null`?

Thanks for replying.

**Comment by freekmurze** [comment]
It honestly don't know why we made that decision anymore. I guess that we found always returning a string feels clean.

**Comment by skandu81** [comment]
Hello @freekmurze 
is there any way to get the value directly 
actually I had stored all my data without the use of laravel-translatable and now I'm storing data by laravel-translatable so the problem is that I'm getting null value where I had not used laravel-translatable

**Comment by sdebacker** [comment]
This pull request fix this behavior: https://github.com/spatie/laravel-translatable/pull/427
