### ISSUE TITLE
Return translated model

### ISSUE THREAD

**Issue by margaritacoco** [spatie/laravel-translatable#196]
Is is possible to return a translated Model based on a locale?

The goal is to ideally build a resource, based off a translated model. As a resource is only used for models, since i'm working with an API and resources.

The best case scenario, would be to return the whole model with the translated available fields AND also keep the others.

Thank you everybody!

**Comment by SmirnovMaxim** [comment]
You can use method `getTranslations('attribute')` for get all translates or `getTranslate('attribute', 'lang')`

![image](https://user-images.githubusercontent.com/9385067/74331920-b5027080-4da5-11ea-8a93-cbc58ca26f82.png)

**Comment by margaritacoco** [comment]
> You can use method `getTranslations('attribute')` for get all translates or `getTranslate('attribute', 'lang')`
> 
> ![image](https://user-images.githubusercontent.com/9385067/74331920-b5027080-4da5-11ea-8a93-cbc58ca26f82.png)

A member on Discord gave me a similar suggestion. I totally didn't think about working within the resource, but instead I was trying to bring the content to the resource file.

This is the solution, or simply request the attribute(w/o the "getTranslations()") and it will return the content based off the current Locale for others reading this.


Thank you!

**Comment by RaJiska** [comment]
I'm encountering the same issue and I'd rather like to know if there is some sort of native way of doing this. Doing the `toArray` function requires to edit the function every time the model is modified, therefore adding unnecessary work.

Is there some way to return a translated model in an elegant way ?
