### ISSUE TITLE
Translatable nullable field converted to array instead of object

### ISSUE THREAD

**Issue by vabreuvarela** [spatie/laravel-translatable#200]
Having a bug when the translatable field is set as null, using Laravel 6.12 and spatie/laravel-translatable 4.2

Two translatable fields, name and description. 
Description is nullable.

When doing: 

```
News::create([
   'name' => [
      'en' => 'Voluptas quia in perferendis omnis.h',
      'nl' => 'Voluptas quia in perferendis omnis.'
   ],
   'description' => []
]);
```

The record being stored in the database is as follows:
[Image](https://prnt.sc/rcoqov
)

Even when using:
`protected $casts = ['name', 'description'];`

Still retrieving an array instead of an object while fetching the record.
[](https://prnt.sc/rcot0k)

Is it possible to get an empty object instead of an empty array?

**Comment by avgkudey** [comment]
did you found a solution?

**Comment by nielsiano** [comment]
To anyone ending up here, you could override `getTranslationsAttribute()` and cast empty translations to an object:

```php
    public function getTranslationsAttribute(): array
    {
        return collect($this->getTranslatableAttributes())
            ->mapWithKeys(fn(string $key) => [
                $key => $this->getTranslations($key) ?: (object) []
            ])->toArray();
    }
```
