### ISSUE TITLE
Set mutator bug

### ISSUE THREAD

**Issue by bbprojectnet** [spatie/laravel-translatable#202]
Steps to reproduce:

1. Define set mutator (e.g. `$this->attributes['field'] = strtolower($value)`).
2. Assign some translations.
3. Try to use `forgetTranslation` or `forgetAllTranslations` or assign multiple translations to field (`$model->field = ['en' => 'foo', 'pl' => 'bar']`).

**Comment by freekmurze** [comment]
Could you PR a failing test for us to fix? Or even better: PR a fix with some tests 👍

**Comment by zehntinel** [comment]
[Add possibility to set several translations on Model property #212](https://github.com/spatie/laravel-translatable/pull/212)

- Assign multiple translations to field **($model->field = ['en' => 'foo', 'pl' => 'bar'])** on field with a mutator  **(e.g. $this->attributes['field'] = strtolower($value))**

**Comment by zehntinel** [comment]
[Fix set several translations on Model property #202](https://github.com/spatie/laravel-translatable/pull/215)

**Comment by freekmurze** [comment]
Fixed in the latest version.
