### ISSUE TITLE
1305 FUNCTION json_unquote does not exist 

### ISSUE THREAD

**Issue by AjithLalps** [spatie/laravel-translatable#208]
I got this error while running on the server. this issue occurred because of my MySQL client version. On my server, MySQL client version is 5.1.73. So `laravel-translatable`s which version supports MySQL 5.1.73.

Laravel version 5.8.38
PHP version 7.2.7
MySQL version 5.1.73

**Comment by freekmurze** [comment]
Try upgrading to mysql 5.7

**Comment by AjithLalps** [comment]
Any older version of this package to fix this issue? My server did not come up with MySQL 5.7, So I raised a ticket for this version. because of this issue, I can't run my project on server.
