### ISSUE TITLE
Where has translation ?

### ISSUE THREAD

**Issue by ahmadyousefdev** [spatie/laravel-translatable#209]
Hi!
Is there a way to only list translated content from a model?

for example, this line
```
Content::where('published',true)->orderBy('created_at', 'desc')->get();
```
will list all the content in my model.

let's say the field `title` in `Content` model is translatable, is there a way to **list all** the content where `title` is in a specific language?

**Comment by ahmadyousefdev** [comment]
I managed to solve it like this
```
$locale = Config::get('app.locale');
Content::where('title->'.$locale, '<>', '')->where('published',true)->orderBy('created_at', 'desc')->get();
```

But is there a cleaner way supported by this package ?

**Comment by rromaniv** [comment]
Ia there another solution for this problem?
