### ISSUE TITLE
Disable fallback location in config

### ISSUE THREAD

**Issue by ehsanrasta** [spatie/laravel-translatable#213]
If in config file set fallback locale to null then package will use application fallback locale and there is no way to disable this option globally.
I knew that I can pass false to getTranslation method but it would be nice to disable this option in config instead of repeating false everywhere.

**Comment by ctf0** [comment]
for now, extend the trait and override the `getTranslation`

**Comment by mcanvar** [comment]
Please consider reopening this issue. This config would be very helpful. Thank you.
