### ISSUE TITLE
Mb str to upper

### ISSUE THREAD

**Issue by ayman-elmalah** [spatie/laravel-translatable#219]
When i use this package to do translation in the model
i validate the key as required and array

when the array key is not in the dom it must return that it's required as usual without package

but when i use the package it return error that mb_strtoupper() expects parameter 1 to be string, array given

the first attatched image of validation of key
and the second when sending request without sending the array

![1](https://user-images.githubusercontent.com/22693197/87302433-af09ea80-c511-11ea-8699-8b63daa2d792.PNG)
![2](https://user-images.githubusercontent.com/22693197/87302435-b03b1780-c511-11ea-94a2-0765c03d3f66.PNG)

**Comment by freekmurze** [comment]
Could you submit a failing test for us to fix?
