### ISSUE TITLE
Cached model returns plain JSON instead of translation

### ISSUE THREAD

**Issue by lasseeee** [spatie/laravel-translatable#220]
Whenever i cache a model that has translations stored in a JSON column, I get pure JSON back instead of the translated attribute. When i use the `getTranslation()`  method directly instead of relying on the accessor, I get: `Call to undefined method stdClass::getTranslation()`.

Is caching supported? I can't seem to find anything in the docs.

**Comment by freekmurze** [comment]
The package does nothing special regarding caching. 

If there is something that can be done in the package to solve your problem, please submit a PR with tests.
