### ISSUE TITLE
[Feature] Fallback to first available translation

### ISSUE THREAD

**Issue by lucianholt97** [spatie/laravel-translatable#224]
### Problem:
When querying a translatable string which only has a translation in one specific language which does not match the requested language or the fallback language you end up having an empty string.  
This is worse UX than having a translation in the "wrong" language.

### Solution:
Add an option (or even default) to fall back to the first available translation when neither the requested nor the fallback locale matches. Prevent empty strings...

### Code Example:
```
public function getTranslation(string $key, string $locale, bool $useFallbackLocale = true)
{
        $locale = $this->normalizeLocale($key, $locale, $useFallbackLocale);

        $translations = $this->getTranslations($key);
        if (count($translations) > 0) {
            $translation = $translations[$locale] ?? array_values($translations)[0];
            if ($this->hasGetMutator($key)) {
                return $this->mutateAttribute($key, $translation);
            }
            return $translation;
        } else {
            return '';
        }
}
```

**Comment by mauriciovillam** [comment]
I have this issue too, it's possible to circumvent it with some extra code but I guess it's something that should be provided by the package. The code example looks good!

**Comment by indigoram89** [comment]
+1

It is a very important feature!

I think about fork the package because of this.

Please do it.

**Comment by freekmurze** [comment]
Feel free to PR this with tests and an updated readme. The new behaviour should be opt in (so no breaking changes please), maybe you can add a new config key to enable it for people who need it.

**Comment by indigoram89** [comment]
Can someone do this PR?

**Comment by freekmurze** [comment]
@indigoram89 People who thin it's an important feature could do it 👍

**Comment by indigoram89** [comment]
@freekmurze I created pull request, can you check it please?

**Comment by freekmurze** [comment]
We'll continue this in #236
