### ISSUE TITLE
Using MariaDB

### ISSUE THREAD

**Issue by denjaland** [spatie/laravel-translatable#23]
Hi guys.

Wonderful library.  
We're using MariaDB in stead of MySQL.  I don't think it supports the json data type.

How does the library work when it is using text columns when we are querying with a where clause?
Am I right in thinking that it fetches the data from the database doing a where column like '%searchstring%' and then you're filtering in code?

**Comment by freekmurze** [comment]
Like mentioned in the readme file, you can also add `text` columns instead of `json` columns. If it doesn't work in Mariadb, let me know.

**Comment by denjaland** [comment]
Hi @freekmurze 

Yes - I read that - I was just wondering how it worked under the hood when we are working with regular text columns.  As you can not query on the json object in the database - how do you query when I pass along a where clause for a translated column.

Are you getting everything where the column LIKE '%searchstring%" and then filter in code based on the translated value?  It was more a question about how we'd be able to use your class without risking to run into performance issues when we notice that for these searches the retrieve on database level becomes to much of a overhead.

**Comment by denjaland** [comment]
Ridiculous example, but what if we have stored the following translated attribute:

{nl: 'aaa', en: 'bbb'}

and we have our locale set to EN
when we do model::where('attribute', 'aaa')
we do not want to get this model back, because we are querying in English.

If we are using text columns, the database will obviously return the data; will your class postprogress the returned collection when it is on the server?  When I browse the code, I don't think it will, and the value 'bbb' will be returned even though we searched for 'aaa' right?

May be a nice addition to filter the results returned by the database in the code :-)
I hope that clarifies my question a bit :-)

**Comment by denjaland** [comment]
(by the way: json is on the roadmap voor mariadb 10.2 ;-) )

**Comment by freekmurze** [comment]
When we were still using Maria db, we used this query to search over translated attributes (in this case the `url` field)

https://github.com/spatie-custom/blender/blob/a0ef704a9713a7a85d24dd8424638e3aa0e6847f/app/Foundation/Repositories/Repository.php#L49-L54

**Comment by denjaland** [comment]
THanks for that, @freekmurze.
You moved away from MariaDB?  What did you replace it with?  Any link on your blog that sheds more light on the reason for this discussion? #alwaysinterestedtolearn

**Comment by freekmurze** [comment]
We moved back to MySQL specifically for the `json` support 😄

**Comment by denjaland** [comment]
Lol - makes perfect sense!  I was actually considering it myself, but we can wait a bit and it is scheduled for maria 10.2, so we'll probably sweat it out ;-)

**Comment by Nuranto** [comment]
For new users : You can use json functions in Mariadb 10.2, 10.3 and the last 10.4, like JSON_EXTRACT.
However, json operators -> and ->> ar not supported yet (see https://jira.mariadb.org/browse/MDEV-13594)

@freekmurze It may be usefull to edit the doc to show an example with JSON_EXTRACT function ?
