### ISSUE TITLE
WithLocale collisions with HasTranslatableSlug in laravel-sluggable 

### ISSUE THREAD

**Issue by YannikFirre** [spatie/laravel-translatable#230]
Hello,

Since the new release and the pull request #229 the package collides with the Localizable trait in spatie/laravel-sluggable package.

Is it possible to rename one of the methods or do you think of another solution?

Thank you :)

**Comment by freekmurze** [comment]
Which method collides? I'd accept a PR that renames the colliding methods. I'm aware that these changes will be breaking, so I'll only accept such a PR if it is submitted in the next few days.

**Comment by YannikFirre** [comment]
Hello @freekmurze :) 

The method is WithLocale in here : https://github.com/spatie/laravel-translatable/blob/master/src/HasTranslations.php#L14

But it's not with sluggable package but with laravel itself with the trait Localizable here :  https://github.com/laravel/framework/blob/43bea00fd27c76c01fd009e46725a54885f4d2a5/src/Illuminate/Support/Traits/Localizable.php#L16

And it's used in sluggable here : https://github.com/spatie/laravel-sluggable/blob/master/src/HasTranslatableSlug.php#L10

**Comment by freekmurze** [comment]
In the latest release, I've renamed `withLocale` to `usingLocale`.
