### ISSUE TITLE
Translated columns are casts to array

### ISSUE THREAD

**Issue by GuidoHendriks** [spatie/laravel-translatable#234]
In this package there are casts for each translated columns to `array`. Is there a reason for this? I would expect a cast to `string` instead.

The reason why I'm asking this is because I'm using the IDE helper package (https://github.com/barryvdh/laravel-ide-helper) which uses the casts for generating the phpDoc. Translated fields show up as `array` in there.

https://github.com/spatie/laravel-translatable/blob/b402293d34965e58ef8f38a8434a752196a45f6e/src/HasTranslations.php#L234-L240

The cast type doesn't affect any tests, they all succeed with both `array` and `string`.

**Comment by freekmurze** [comment]
If all test works, than using `string` is fine with me. Send a PR to change that.
