### ISSUE TITLE
Uninitialized string offset: 0 On Trans.

### ISSUE THREAD

**Issue by PandaTechTeam** [spatie/laravel-translatable#237]
While I Try To Access 
```$row->name;```
I Got The Name In Local Lang. 
But When I Tried To Access First Letter As
```$name=row->name; $name[0];```
I Got ```Uninitialized string offset: 0```
Tried ```substr($row->name, 0, 3)```
And I Got What I Want 
But Why I Could not Access It Like **$name[0]** 
As Your Function Return String
I Knew It May Not Be An **Issue** 
But I Just Wanna Understand

**Comment by freekmurze** [comment]
I don't understand the issue. Please PR a failing test for me to look at.
