### ISSUE TITLE
Can't retrieve translation for pivot table column.

### ISSUE THREAD

**Issue by purplman** [spatie/laravel-translatable#243]
I have many to many relation between product and attribute tables, and the pivot table has a value column which is translatable. ProductAttribute model is configured correctly, but for some reason, the value returns the JSON, not the translation. 
![1](https://user-images.githubusercontent.com/58288990/100548447-1092e180-3286-11eb-8e25-22270e4519d9.jpg)
![2](https://user-images.githubusercontent.com/58288990/100548451-12f53b80-3286-11eb-812f-9f549bec0c03.jpg)

**Comment by ZaidBarghouthi** [comment]
How are you storing and retrieving `value` ?

**Comment by purplman** [comment]
@ZaidBarghouthi the pivot table has `product_id`, `attribute_id` and `value` columns. `Value` column is `$translatable`. I retrieving it with `$product->pivot->value`. I get the value in json as you can see.

**Comment by purplman** [comment]
Product and Attribute have a many-to-many relation. I found a workaround. So instead of calling it as a pivot column, I made a new relation with pivot and product table with one-to-many relation. For some reason, pivot columns are not translated.
