### ISSUE TITLE
Search for Arabic records

### ISSUE THREAD

**Issue by jadayash** [spatie/laravel-translatable#244]
Hello

Am using spatie/traslatable in my project and storing arabic text in my database.
The issue is how can i search for arabic text in the translatable cols?

They are being stored in that encoding
![ggggg](https://user-images.githubusercontent.com/66420205/100806327-ed5c6380-3438-11eb-91ea-935883bd30b6.PNG)

**Comment by ZaidBarghouthi** [comment]
I am using it to store Arabic text as well. There is no problem in searching though! I believe this is **UTF-32 encoded**.

Since the field is json you can just query like this: 
```php
Model::query()->where('title->ar', 'like', '%'.$search.'%');
```

or just loop all translations in the query:

```php
$translations = ['ar', 'en'];

$qry = Model::query();

foreach($translations as $translation) {
    $qry->where('title->'.$translation, 'like', '%'.$search.'%');
}
```

**Comment by jadayash** [comment]
Thanks alot
Working Great
