### ISSUE TITLE
`usingLocale` method not working during `create` action

### ISSUE THREAD

**Issue by biscolab** [spatie/laravel-translatable#255]
Hi, `usingLocale` method apparently is not working.
I added `Spatie\Translatable\HasTranslations` trait to `MyModelClass ` class and: 
```php
public $translatable = [
        'title',
        'description',
];
```
Creating a new object with following code:
```php
$item = MyModelClass::usingLocale('fr')->create([
    'title' => 'French title',
]);
```
I expect to get the following `$item->title`:
```php
[
    "fr"=> "French title" 
]
```
but actually, the value is:
```php
[
    "en"=> "French title" 
]
```

PHP 7.4.13
Laravel Framework 8.20.1
spatie/laravel-translatable 4.6.0

Thanks.

**Comment by akiyamaSM** [comment]
I can confirm that too.

**Comment by samehdoush** [comment]
I can confirm that too.  
error : 

```
ErrorException 

  Array to string conversion

  at C:\xampp\htdocs\company\vendor\laravel\framework\src\Illuminate\Support\Str.php:509

         $result = array_shift($segments);

         foreach ($segments as $segment) {
           $result .= (array_shift($replace) ?? $search).$segment;
        }

        return $result;
        }
```

**Comment by mohamedsabil83** [comment]
Hi @freekmurze, this issue still occurred.
Can you take a look? I tried to fix it but without success.
