### ISSUE TITLE
get Translated from model attribute

### ISSUE THREAD

**Issue by MahdiPishguy** [spatie/laravel-translatable#263]
you suppose i have this code:

```php
$category = Category::find(1);
```

which that return `title` and `description` with 4 language translated into them. now how can it get them from each model attribute? for example:

```php
$en = $category->title->en;
```

**Comment by totiherms** [comment]
explained here 

https://github.com/spatie/laravel-translatable#automatically-display-the-right-translation-when-displaying-model

**Comment by MahdiPishguy** [comment]
Hi I think you didn't  get my meant. I want to get one of each translate
from model attribute which that saved into database Not all attribute
translates.
