### ISSUE TITLE
getTranslations() must be of the type array, string returned

### ISSUE THREAD

**Issue by herzcthu** [spatie/laravel-translatable#27]
getTranslations() must be of the type array, string returned when model is already saved and translatable column value is null.

**Comment by freekmurze** [comment]
Could you PR a test the demonstrates the bug?

**Comment by sebastiandedeyne** [comment]
Are you sure the column is actually `NULL` and not an empty string?

**Comment by sebastiandedeyne** [comment]
Closing this for now. Feel free to reopen if you're still having issues.
