### ISSUE TITLE
UTF-8 escaped as \uXXXX

### ISSUE THREAD

**Issue by jorenvanhee** [spatie/laravel-translatable#28]
When inserting translations, this word for instance `Abée`, gets transformed to `Ab\u00e9e`. This behaviour can be changed by overwriting the `asJson` method on the `Eloquent\Model` class.

```php
public function asJson($value)
{
    return json_encode($value, JSON_UNESCAPED_UNICODE);
}
```

I guess this package shouldn't worry about this and we should fix this ourselves?

Also, search could be tricky if we try searching for `Abée`.

**Comment by sebastiandedeyne** [comment]
This is something that should be dealt with outside of this package, since Eloquent handles the actual casting, and this package shouldn't need to care about the database's encoding.

**Comment by elephantux** [comment]
This line https://github.com/spatie/laravel-translatable/blob/master/src/HasTranslations.php#L98
must be:
```
$this->attributes[$key] = $this->asJson($translations, JSON_UNESCAPED_UNICODE);
```

**Comment by elephantux** [comment]
@jorenvanhee just add this to your translatable model:
```
protected function asJson($value)
{
   return json_encode($value, JSON_UNESCAPED_UNICODE);
}
```

**Comment by MahdiPishguy** [comment]
> This is something that should be dealt with outside of this package, since Eloquent handles the actual casting, and this package shouldn't need to care about the database's encoding.

the problem wasn't outside of this package ;)
