### ISSUE TITLE
Attribute doesn't cast to proper translation when converting to JSON

### ISSUE THREAD

**Issue by jonkootje** [spatie/laravel-translatable#282]
When I convert a model into a JSON string, the translatable attributes are shown in the raw format (object containing all the different translations). I would expect for it to return the translation string based on the current app locale.

**Comment by freekmurze** [comment]
Feel free to PR improvements around this.

**Comment by denizozturk** [comment]
> When I convert a model into a JSON string, the translatable attributes are shown in the raw format (object containing all the different translations). I would expect for it to return the translation string based on the current app locale.

The issue hasn't been closed for a long time, is the problem you are still experiencing?

**Comment by VSG24** [comment]
I'm having the same problem. For example, if I have a translatable model named Category, the following would return an undesirable output:

`Category::first()->toArray();`

returns

`['id' => 1, 'title' => ['en' => 'my category']`

**Comment by denizozturk** [comment]
You can fetch the string returned by the model according to the current language.

[Automatically display the right translation when displaying model](https://github.com/spatie/laravel-translatable#automatically-display-the-right-translation-when-displaying-model)

**Comment by VSG24** [comment]
@denizozturk You're right. I think we can consider this matter solved.

**Comment by goiglesias** [comment]
Hi!
I've a model "Certificacion" that is translatable in field "titulo" (title):
![image](https://user-images.githubusercontent.com/77011228/131834806-ce0191ce-7c86-47e6-9bb9-eaad43a48500.png)
I've another model "Examen" (no translatable) joined to "Certificacion", like this (see line 514):
![image](https://user-images.githubusercontent.com/77011228/131835042-4c8dff42-b261-40e8-86d7-6c82107211b5.png)
When call this method in a Controller I get a Collection of "Examen", but "titulo" is not translated:
![image](https://user-images.githubusercontent.com/77011228/131835203-65c121a5-26c8-4c83-acfc-9053412682d7.png)

Is it the same issue? What I'm doing bad? How can I solve?
Thanks!
@freekmurze

**Comment by hieuhtse05008** [comment]
Is there anyway to skip the translation? I'm using a repository to transform the model but the repository uses toArray() method and it won't return all translations.

**Comment by freekmurze** [comment]
Closing as @VSG24 confirmed that this is solved. @hieuhtse05008 please open up a q&a discussion for new questions.
