### ISSUE TITLE
Use fallback locale for missing translations

### ISSUE THREAD

**Issue by finikm** [spatie/laravel-translatable#3]
In the documentation you mention that "If there is no translation set the value of `default` will be returned.", but the function definition is different in `HasTranslations` function and there's no way to set the default locale.

Is it possible to use the `fallback_locale` for the missing translations?

**Comment by freekmurze** [comment]
Currently there is no support for `fallback_locale`. We'll add that to the package soon and also fix the docs.

**Comment by freekmurze** [comment]
Support for a fallback has been added in v1.1.0
