### ISSUE TITLE
Use Laravel's fallback_locale config as fallback locale

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-translatable#30]

**Comment by freekmurze** [comment]
We'll revisit this when creating a new major version.

**Comment by ankurk91** [comment]
Laravel v5.8 is coming in March.

So lets -
* Release v4.x
* Drop php 7.1 support
* Use `app.fallback_locale`

**Comment by freekmurze** [comment]
I'd accept a PR for this ⬆️
