### ISSUE TITLE
Model not saved after forget translation

### ISSUE THREAD

**Issue by gillesboisson** [spatie/laravel-translatable#303]
## Context 
Laravel 8.40
Php 8.0
spatie/laravel-translatable 5.0.3

I use postgres DB, translation is a postgres json field. 

## Issue
When I use forget translation eg. `$model->forgetTranslation('field','fr')` and when it was the only model translation left, after saving the model is not saved. I checked translations state just before save and it seams to be ok, but after checking model->saving steps, translation attribute seams to be found as dirty. 

I don't have the issue if attribute has others translations (eg. `{"fr":1,"en":2} > {"en" : 2 }`) 

Cheers,

**Comment by stefanocurnis** [comment]
I can confirm the problem. It does not work when you are going to forget a translation that is the only one translation in the field.

**Comment by stefanocurnis** [comment]
```
    public function forgetTranslation(string $key, string $locale): self
    {
        $translations = $this->getTranslations($key);

        unset(
            $translations[$locale],
            $this->$key
        );

        if(!array_key_exists($key,$this->attributes)){
            $this->attributes[$key] = null;
        };

        $this->setTranslations($key, $translations);

        return $this;
    }
```

This would solve it. right now the field is being completely removed from the object. so Laravel is not detecting it as dirty and it won't save.
