### ISSUE TITLE
How to return only one locale 

### ISSUE THREAD

**Issue by myounis97** [spatie/laravel-translatable#320]
Hello, first of all, thank you for your great work as usual,

I have  a question how can I return only one locale when dealing with REST API here is an example: 

`public function index(Request $request)
    {
        return $this->repository->simplePaginate();
    }`

Here is the response:
`{
            "id": 9,
            "name": {
                "en": "Books, Tools & Kids",
                "ar": "et"
            }
        }`

I want it to be like this if app locale is en for instance
`{
            "id": 9,
            "name":  "Books, Tools & Kids"
        }`

Thanks and Regards,

**Comment by anibalealvarezs** [comment]
Hello.

You can use [mutators](https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator) for customizing attributes.

```php
// For attribute "name" in "YourModel.php":

// as object
public function getNameAttribute($value)
{
    return  json_decode($value)->{app()->getLocale()}
}

// or as array
public function getNameAttribute($value)
{
    return  json_decode($value, true)[app()->getLocale()]
}
```

Considering that you could have added some values in your tables by different means so the value for the column is not a JSON object (it has no translation), you could check previously the validity of the JSON. So, this option would be more robust.

```php
// For attribute "name" in "YourModel.php":

public function getNameAttribute($value)
{
    if ($json = json_decode($value)) {
        return $json->{app()->getLocale()}
    }
    return $value;
}
```

**Comment by myounis97** [comment]
> Hello.
> 
> You can use [mutators](https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator) for customizing attributes.
> 
> ```
> // For attribute "name" in "YourModel.php":
> 
> // as object
> public function getNameAttribute($value)
> {
>     return  json_decode($value)->{app()->getLocale()}
> }
> 
> // or as array
> public function getNameAttribute($value)
> {
>     return  json_decode($value, true)[app()->getLocale()]
> }
> ```
> 
> Considering that you could have added some values in your tables by different means so the value for the column is not a JSON object (it has no translation), you could check previously the validity of the JSON. So, this option would be more robust.
> 
> ```
> // For attribute "name" in "YourModel.php":
> 
> public function getNameAttribute($value)
> {
>     if ($json = json_decode($value)) {
>         return $json->{app()->getLocale()}
>     }
>     return $value;
> }
> ```

Thanks a lot
