### ISSUE TITLE
cant able to translate pluck elequent 

### ISSUE THREAD

**Issue by devgene** [spatie/laravel-translatable#321]
cant able to translate pluck elequent

**Comment by anibalealvarezs** [comment]
Hello.

[hasTranslation](https://github.com/spatie/laravel-translatable/blob/main/src/HasTranslations.php) is a trait for Models.

You should add a [mutator](https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator) for the field you want to be translated, so pluck filters the already translated field.
