### ISSUE TITLE
"HasTranslations" does not work for me

### ISSUE THREAD

**Issue by Bekzhan99** [spatie/laravel-translatable#338]
I want to get only "ru", but it gives me all of this.
![image](https://user-images.githubusercontent.com/47516570/158567180-e7e3e5fd-edfa-49af-b47c-8fa99e8ea5af.png)
![image](https://user-images.githubusercontent.com/47516570/158567099-f9824bbf-3570-4f7e-870d-9b1a3c921a8b.png)

What I expected to happen
app->getLocale('ru);

data : {
"title" : "asssssssssss",
....
}

**Comment by anibalealvarezs** [comment]
Hello.

Check this other issue: https://github.com/spatie/laravel-translatable/issues/320#issuecomment-1017410024

**Comment by Bekzhan99** [comment]
@anibalealvarezs  Sorry. i wrote a function "getNameAttribute" to the module but not go inside. how to solve this problem?

![image](https://user-images.githubusercontent.com/47516570/158574737-cea0e8de-2ed8-48f9-8688-7f57320f83e0.png)
![image](https://user-images.githubusercontent.com/47516570/158574793-5237daf0-78bc-4e9f-b0e6-c07860f7a75f.png)

**Comment by anibalealvarezs** [comment]
Hello.

Check documentation about mutators for deep understanding about it: https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator

But, simplifying, the magic method should be constructed based on the attribute name. For example:

For ```title``` attribute:
```php
public function getTitleAttribute($value)
{
 // Your code here
}
```

The idea is to format the output for every attribute you have marked as translatable.

**Comment by Bekzhan99** [comment]
Thank you
