### ISSUE TITLE
Prepare for frontend

### ISSUE THREAD

**Issue by apocalyarts** [spatie/laravel-translatable#35]
Is there an easy way to prepare translatable models for the frontend? Let's say I have a product with a translatable title, if I return $products->toJson() in my API, the title attribute is a JSON array. 

So to work with the objects in my frontend, I have to call App::getLocale(), pass the value seperately to my frontend and then rework all my custom Vue components to accept a locale, so I can access the translated attribute with product.title[locale]

It would be great to have automatic attribute casting to the current locale when calling toArray() or toJson(). Sorry if this is not an issue directly but I am not clever enough to create a PR for this :D

**Comment by sebastiandedeyne** [comment]
I think you could write accessors to retrieve the value instead of the translation set:

```php
public function getNameAttribute()
{
    return $this->getTranslation('name', app()->getLocale());
}
```

Alternatively, you could use something like [Fractal](https://github.com/spatie/laravel-fractal) or a plain `->map(...)->toJson()` to sanitize your data before sending it to the front end (that's how we generally handle issues like this).

**Comment by apocalyarts** [comment]
Writing an Accesor or directly replacing the attributes while using ```map()``` won't work. 

The problem is that all attributes from the ```$fillable``` variable will be declared as array for casting. 

So as soon as I call ```toJson()``` or ```toArray()```, Laravel will crash.

**Comment by sebastiandedeyne** [comment]
Not the prettiest solution, but this seems to work:

```php
protected $fillable = ['description'];

protected $translatable = ['description'];

public function getDescriptionAttribute($value): string
{
    return json_decode($value, true)['en'];
}
```

**Comment by cayaner** [comment]
it works, but i believe it would be nice to be the default behavior. thanks ..

**Comment by ggirodda** [comment]
I have the same problem, and don't really like this solution because I have to write an accessor for every translatable field. Is there a new way to do this ?

**Comment by mcmc4519** [comment]
I wrote my trait, and add default behavior for frontend 

`<?php

namespace App\Traits;

use App;


trait HasTranslationsTrait
{
    private $translations_replaced;
    use \Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations;


    /**
     * Magic method to get the db entries already translated in the wanted locale.
     *
     * @param string $method
     * @param array $parameters
     * @return
     */
    public function __call($method, $parameters)
    {
        $data = parent::__call($method, $parameters);

        $request = request();
        $isJson = $request->segment('1');
        // if request is from frontend
        if ($isJson === 'json') {
            switch ($method) {

                case 'hydrate':

                    $data = $data->map(static function ($row) {
                        $row->prepareTranslate();
                        return $row;
                    });
                    break;
                default:
                    break;
            }
        }
        return $data;
    }

    private function prepareTranslate()
    {
        $locale = getCurrentLocale();
        $attributes = $this->getAttributes();
        foreach ($attributes as $attribute => $value) {
            if ($this->isTranslatableAttribute($attribute)) {
                parent::setAttribute($attribute, $this->translate($attribute, $locale));
            }
        }

        return $this;
    }

}
?>
`
