### ISSUE TITLE
Is there any practical way to use this package with existing database?

### ISSUE THREAD

**Issue by yusufyilmaz** [spatie/laravel-translatable#37]
Thank you for the package. I have used dimsav's package for multilingual for a quite time. And I have a project which I want to add support for multilingual models and I dont want to create second table for every table in my database. 

So you package seems quite good for my purpose. But I wonder if I can use this package with an existing database. Some of columns are varchar fields and some are text fields. I cannot alter table to json column type easily. Do you have a practical way to do this and use your package?

**Comment by yusufyilmaz** [comment]
Well, I have tested my question and it does not work with existing table values. They need to be converted as json format. So I have updated one model's columnt as

`UPDATE my_table SET title=CONCAT('{ "tr": "', REPLACE(title, '"', '\\"'), '"}')`

In the `my_table`, `title` field is the column that I want it act as translatable. So it worked like charm with this procedure. Now I have around 65 tables to adjust for such behavior :)

Do you think that would it be a good way to have an artisan command to convert models which have `Hastranlations` trait, to json format depending on application locale?

**Comment by sebastiandedeyne** [comment]
Since this is a one-time transformation from an old database structure to a new one, writing a migration that executes those statements would make sense I think.
