### ISSUE TITLE
  Invalid version string "^8.0.2"

### ISSUE THREAD

**Issue by tugrandemirel** [spatie/laravel-translatable#409]
When I try to install the package to my project, I get the error `Invalid version string "^8.0.2"`. i did a composer self-update, but it didn't work out. does anyone know the solution to the error? Can you help me?

composer.json
` "require": {
        "php": "^8.0.2",
        "biscolab/laravel-recaptcha": "^5.4",
        "ccxt/ccxt": "^1.53",
        "doctrine/dbal": "^3.5",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.2",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7"
    },`

**Comment by mabdullahsari** [comment]
You'll need to provide a bit more info. Do you still have the same problem?
