### ISSUE TITLE
error when using with query builder

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-translatable#41]
the main reason behind this is using the query builder instead of eloq
```php
DB::table('posts')->first()->getTranslation('title', 'en');
```
which return a `StdClass` instead and therefore u get the error
```bash
Call to undefined method stdClass::getTranslation()
```
while using
```php
Post::first()->getTranslation('title', 'en');
```
works as expected, so is there any chance to extend the support to work with `DB::table()` as well ?

**Comment by freekmurze** [comment]
Most people won't need this functions on the query builder itself, so I'm probably not going to include support for that in this package.
