### ISSUE TITLE
case insensitive search in JSON column

### ISSUE THREAD

**Issue by langeuh** [spatie/laravel-translatable#44]
Hey,
I'v been struggling with this for a while so I was wondering what your approach is.

How to query JSON columns in a case **insensitive** manner?

JSON is stored in a binary column, so it's treated as case sensitive. And collation can't be changed to eg 'utf8_unicode_ci'
assuming this content in a JSON column
```json
{
	"en": "Chair",
	"fr": "Chaise",
	"nl": "Stoel"
}
```

These will  return zero results:
```sql
select * from `products` where `name`->'$.nl' like '%stoel%';
```

Changing the column to 'TEXT' with a 'utf8_unicode_ci' collation only works half and loses the benefit of the JSON column type

```sql
select * from `products` where `name` like '%stoel%'; # works, but can't be used
select * from `products` where `name`->'$.nl' like '%stoel%'; # no results
```

This works, but is  hard to implement on a global scale:
```sql
select * from `products` where `name`->'$.nl' COLLATE utf8mb4_unicode_ci like '%stoel%';
```

Any thought on how to implement this easily in Laravel? 
Or even an idea on how you implement a search in a site using JSON columns for eg product names would be really helpful to a lot of people.

Internet seems to lack solutions of people with the same problem
Thanks

**Comment by freekmurze** [comment]
I haven't come across this problem yet. All my searches are case sensitive. 

Try asking your question on a mysql forum.  If you find a good solution please post it here for the other uses of the package.

**Comment by coppee** [comment]
Hi @langeuh ! Did you find a solution ? Big thanks.

**Comment by langeuh** [comment]
No. I just use the query from above. :(

**Comment by gerciljunio** [comment]
@langeuh @coppee 

I did like this:

```php
// "name" is the column in json
$query->whereRaw('LOWER(name) like ?', ['%'.strtolower($query).'%'])
```

unfortunately I can not specify which language I want to search, so it searches in all languages, but it works for me and maybe it works for yours.

**Comment by iparrabb** [comment]
Maybe:

```php
$locale = app()->getLocale();
$builder
    ->whereRaw("json_extract(LOWER(title), \"$.$locale\") LIKE convert(? using utf8mb4) collate utf8mb4_general_ci", ['%' . $search . '%']);
```
