### ISSUE TITLE
How handle form request with json field ?

### ISSUE THREAD

**Issue by t-prod** [spatie/laravel-translatable#46]
Hi,

Thanks again for your package. I'm just wondering how I can validate with a form Request cause I've created a JSON field named title and not 'title_fr' or 'title_en'.
How can I do with your package ?
Here is the function store of my controller :

> 
public function store(StoreorUpdateMyModel $request)
    {
        // Fields to translate
        $translatables = ((new MyModel())->translatable);
        // Locales concerned
        foreach ($translatables as $translatable) {
            $translations = [];
            foreach (config('app.locales') as $locale) {
                $translations[$locale] = $request->{$translatable.'_'.$locale};
            }
            $request->merge([$translatable => $translations]);
        }
        $this->affirm($request);
        MyModel::create($this->getRequestsData($request));
        Session::flash('success_message', trans('labels.backend.added_success'));
        return redirect()->route('mymodel.index');
    }
T

hanks for your help

Regards

**Comment by freekmurze** [comment]
Hi, our package does nothing regarding validation.

**Comment by t-prod** [comment]
Hi,

I just would like to develop it. The way to store in Json field is a great idea but if we want to validate the fields we must integrate a field suffixed by the language ex : title_fr, title_en. So the validation I think it's important and I'm working on it right now.

I think it should be 2 traits.

1. GetRules which modify rules if fields are multilang
2. ModifyRequest modify the request to handle with the fields _fr or _en

What do you think ? It could be a good idea ? Don't you use validation in your projects with your package ?

**Comment by ctf0** [comment]
@t-prod have u reached any solution ?

**Comment by t-prod** [comment]
I use a Trait like this :
`Trait GetRules
{
	/**
     * [getRules return model rules if fields are multilang]
     * @return array
     */
    public function getRules()
    {
    	foreach ($this->rules as $field => $rule) {
    		if(in_array($field, $this->translatable)){
	    		unset($this->rules[$field]);
	    		foreach (config('app.locales') as $locale) {
	    			$this->rules[$field.'_'.$locale] = $rule;
	    		}
	    	}
    	}
    	return $this->rules;
    }
}`

On your model :

`use HasTranslations, GetRules;`

And when you do the validate in your controller :

`
$validator = Validator::make($request->all(), $this->owlcarousel->getRules());
`
Regards

**Comment by ctf0** [comment]
how do u tackle the unique rule ?

**Comment by reppair** [comment]
@ctf0 here is what I did after spending 3-4 hours reading  writing custom validation rules and other complicated stuff...

I have a `Page` model which has a translatable `title` attribute, an `<input name=title['bg']>` && `<input name=title['en']>` HTML inputs for editing the translations  the `title` attribute so the data to be validated looks like that: `"title" => array("bg" => "Нова страница", "en" => "Page")`.

In the `FormRequest::class` that I use (for both create and update actions)...

```
public function rules()
{
    request()->method == 'PATCH' || request()->method == 'PUT' 
        ? $id = request()->route()->page->id : $id = null;

    return [
        'title' => 'array|required',
        'title.*' => 'required|min:3',
        'title.bg' => 'required|unique:pages,title->bg,' . $id ?: '',
        'title.en' => 'required|unique:pages,title->en,' . $id ?: '',
    ];
}
```
That works as a charm using **Mysql 5.7** and **Laravel 5.5**. However that is not the case if we try use **Sqlite3**... there is a extension called JSON1 that I managed to use to query the translations like so:

```
sqlite> SELECT title FROM pages, json_each(pages.title) WHERE json_each.value = 'Страница';
{"bg":"Страница","en":"Page"}
```
From that point on it get too complicated for a simple validation of a string.. (at least for starters without much knowledge like me though! :) Switching to MySQL/PostgreSQL cheers!
