### ISSUE TITLE
Model->toArray() and toJSON() return the JSON-string instead of translated content for translatable columns

### ISSUE THREAD

**Issue by SiSt** [spatie/laravel-translatable#47]
When converting a model to an array the translatable columns contain the json string, containing all languages, instead of the translated value.

I've fixed it in my system by changing HasTranslations.php to include:

```
public function toArray()
{
        $attributes = parent::toArray();

        foreach($this->getTranslatableAttributes() as $field)
        {
            $attributes[$field] = $this->getTranslation($key, config('app.locale'));
        }

        return $attributes;
}
```

This works for me. Is there a better way?

**Comment by freekmurze** [comment]
That seems like a good way to go about it.

**Comment by ebisbe** [comment]
I think this coulb be explained in the docs.

**Comment by IlCallo** [comment]
Will this be included in laravel 5.5 library upgrade? It would be really useful

**Comment by freekmurze** [comment]
I'm holding of on implementing this in the package, but I'm open for a PR to the readme.

**Comment by IlCallo** [comment]
You're holding to avoid API breaking changes?
Maybe it's possible to add a second trait like the following? Which is what I did on my project.

    <?php
  
    namespace App\Traits;
    
    use Spatie\Translatable\HasTranslations as BaseHasTranslations;
    
    trait HasTranslations
    {
        use BaseHasTranslations;
    
        /**
         * Convert the model instance to an array.
         *
         * @return array
         */
        public function toArray()
        {
            $attributes = parent::toArray();
            foreach ($this->getTranslatableAttributes() as $field) {
                $attributes[$field] = $this->getTranslation($field, \App::getLocale());
            }
            return $attributes;
        }
    }

Obviously the name must be changed (something like `HasTranslationsDisplayable` or something alike), but in this way it's possible to add the feature avoiding breaking the existing trait.

If not, which kind of PR will you accept for the README? Only a disclaimer like "pay attention, automatic translations won't work when the toArray method is involved" or can we put actual working code like the one SiSt or I have written?

**Comment by freekmurze** [comment]
A code example in the readme is ok by me.
