### ISSUE TITLE
getTranslations() must be of the type array, string returned

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-translatable#51]
I saw the previous issue that was created in this repository but hasn't been solved there yet.

I have the exact same error;

`Type error: Return value of App\Models\Entity::getTranslations() must be of the type array, string returned`

```
    protected $translatable = [
        'meta_title'
    ];
```

```
$table->text('meta_title')->nullable();
```

When I leave the `$translatable` property empty there is no problem.

Error:

```
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of App\Models\Entity::getTranslations() must be of the type array, string returned in /Users/****/Workspace/community/vendor/spatie/laravel-translatable/src/HasTranslations.php:72
```

**Comment by sebastiandedeyne** [comment]
What does the database record look like?

**Comment by Cannonb4ll** [comment]
TEXT field named 'meta_title', thats why I posted the migration line in my initial post.

I am just creating like;

```
$factory->define(App\Models\Entity::class, function (Faker\Generator $faker) {
    return [
        'meta_title' => $faker->text(50)
    ];
});
```

**Comment by sebastiandedeyne** [comment]
If you're using some sort of `create` model for your models, you need to specify the translation array yourself.

Should look like this:

```php
$factory->define(App\Models\Entity::class, function (Faker\Generator $faker) {
    return [
        'meta_title' => ['en' => $faker->text(50)],
    ];
});
```

**Comment by Cannonb4ll** [comment]
I quickly want to come back to this, wouldn't it be an idea to check if the passed type is a string or array? If it would be a string then the package would automatically grab the app.locale key to generate an array. Thoughts on this?

**Comment by freekmurze** [comment]
If you can add this in an easy, non-breaking and fully tested way, sure create a PR.
