### ISSUE TITLE
Removing a language from an object?

### ISSUE THREAD

**Issue by CrixuAMG** [spatie/laravel-translatable#53]
What would be the recommended way of removing a language from an object?
I'm thinking of getting the current locales, removing en/nl/whatever and then saving it, however the current methods don't support this as far as I can see.
Did I miss something or is this functionality missing?

**Comment by freekmurze** [comment]
You can do this with the `forgetAllTranslations` I just added to the package.

**Comment by CrixuAMG** [comment]
Thanks for the update!
