### ISSUE TITLE
Should i use this package on a 10+ languages supporting project?

### ISSUE THREAD

**Issue by moakkaya** [spatie/laravel-translatable#58]
Hi,
Let's say we have 10+ different languages support on a project which has tons of articles, blogs, details etc.

Is it ok to continue with this repo or should i continue with dimsav's?

**Comment by freekmurze** [comment]
Our package can handle 10+ languages and I'm pretty sure Dimsav's can do too. 

The big difference between ours and Dimsav's is that ours stores the translations as json in the db and Dimsav's one uses a seperate table to store translations.

Go through the readme's of both packages and pick which one feels the best to you.
