### ISSUE TITLE
Why not using the default `app.fallback_locale` config option?

### ISSUE THREAD

**Issue by Omranic** [spatie/laravel-translatable#6]
First of all thanks for this awesome package, neat and elegant API. The cleanest, easiest, and most intuitive translatable Eloquent models API actually.

My question is: Why do you duplicate the `fallback_locale` config option and not using the default `app.fallback_locale` for locale fallback, just like the `app.locale` ?

**Comment by freekmurze** [comment]
Hi, thanks for you kind words on our package. Greatly appreciated.

I simply forgot that `app.php` did already contain a `fallback_locale`. Changing this now, would be a breaking change. I'll correct this is the next major version of the package.

**Comment by Omranic** [comment]
Appreciated @freekmurze 

One more thing, are you interested in the following features sent in a PR?
- Add support for multiple translation forgot: `forgetTranslations`
- Fire event on `forgetTranslation` like in `setTranslation`

**Comment by freekmurze** [comment]
Hi, I'd probably accept a PR with those features.
