### ISSUE TITLE
WhereIn not working

### ISSUE THREAD

**Issue by nikkanetiya** [spatie/laravel-translatable#60]
I am using Laravel 5.4. Is there any way to use whereIn on the translatable column.

This works totally fine:-
NewsItem::where('name->en', 'Name in English')->get();

This is not working:-
NewsItem::whereIn('name->en', $names)->get();

Thanks

**Comment by freekmurze** [comment]
Could you PR a failing test for me to look at?

**Comment by nikkanetiya** [comment]
Yes sure, within a day.
