### ISSUE TITLE
How to perform like search? 

### ISSUE THREAD

**Issue by harshalsathavara** [spatie/laravel-translatable#61]
Wonderful package, thank you. 

The are two things we want to know 
1) Does this package stores data in unicode format like \uxxxx format only? Say I want to store नमस्ते दुनिया
the does it store as it is or in unicode format? 

2)  We are having following data under `name` filed 
`{"en":"Nokia-130","ar":"\u0646\u0648\u0643\u064a\u0627 130 (2017)","ch":"\u8bfa\u57fa\u4e9a130\uff082017\uff09"}`

We are trying to hit 
`SELECT json_extract(NAME, "$.ar") FROM products WHERE json_extract(NAME, "$.ar") LIKE '%\u0646%'`

it works fine and gives the result but when we hit 

`SELECT json_extract(NAME, "$.ar") FROM products WHERE json_extract(NAME, "$.ar") LIKE '%\u0646\u0648%'` 

it does not work. Can you please help in this? Thank you

**Comment by freekmurze** [comment]
Hi,

I'm glad you like our package 😄 

1. I honestly don't know. Try it out and let me know :-) My gut feeling says `नमस्ते ` would be stored.

2. Sorry to say I can't help you with that one either. The question is also more related to SQL, MySQL and not so much to this package.

**Comment by bhagwatsingh** [comment]
Hi,

You can do this like.

$q->whereRaw("JSON_UNQUOTE(JSON_EXTRACT(`name`, '$.en')) LIKE '%{$request->input('name')}%'");

**Comment by mai1237** [comment]
Add the function below in your Model to avoid  "\u8bfa\u57fa\u4e9a130\uff082017\uff09" and use  नमस्ते दुनिया

    public function asJson($value)
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }
I hope it helps
