### ISSUE TITLE
[Question] Get All Translations

### ISSUE THREAD

**Issue by johannesschobel** [spatie/laravel-translatable#67]
Hey guys,

first of all - nice work on this package. I am considering using this package, however, i would like to get some more information.

Consider the following scenario:
My application stores `FAQ`s in different languages (e.g., en, de, fr, ...) A FAQ entry consists of a `question` and an `answer`, both are texts (obviously).

A regular `User` may browse all available `FAQ`s in his language (by using the `Accept-Language` HTTP Header). However, an `Editor` can create / update `FAQ`s and, therefore, needs the texts of the respective entity in all available languages.

How can i achieve this scenario? Note that I am using your `laravel-fractal` package as well.

For example, I would like to have an `FAQTransformer` that outputs the respective data, like so:

```php
// ... skipping class information
    public function transform(Faq $entity)
    {
        return [
            'id' => $entity->id,
            'question' => $entity->question,
            'answer' => $entity->answer,
        ];
    }
```

Obviously, I could make an additional transformer that uses
```php
// ... 
'question' => $entity->getTranslations('question'),
// ...
```
but that would be redundant code.

It would be perfectly fine for me to set the `Accept-Language' header to `*` or something like that to indicate that i would like to get all entities..

How could one achieve this behaviour? Or how would you tackle this issue?
Thanks a lot and cheers from Germany

**Comment by freekmurze** [comment]
Your question is scoped a bit too broadly for this issue tracker.  

There isn't one true way to solve this.  Does you `Editor` log in? Then you can create different responses for the role of the logged in user. Or you could opt to use a query parameter to have a different result. Or you could have different endpoints all together.

**Comment by johannesschobel** [comment]
Thank you for your reply. However, I **do** believe, that this is a valid scenario.

If one User shall edit all languages of a property (e.g., the `question` and `answer` of a `FAQ`), he must have access to all texts in all languages.

Of course, there are multiple approaches to solve this, however, they all involve having a specific `Transformer` that outputs the data by calling 
```
$entity->getTranslations('question')
```
instead of
```
$entity->question
```

This leads to several issues:
1) You need to have at least 2 `Transformers`: One for a `single language` and one for `all languages`. Of course you could do this in a single `Transformer`, but this results in huge `if/else` blocks.
2) You may need to rewrite logic in your `Controllers` to determine the type of user (e.g., _If the user has the role `Editor` do this, otherwise do that_)
3) It is so ugly 😢 and I feel so much pain by writing such code

Another approach would be to simply make one `GET /faq/1` with various `Accept-Language` headers to get the texts for `de`, `en`, and so on.. But that would significantly slow down the application and increase the amount of HTTP calls. So basically that is not a good approach.

So I think, the scenario _get all languages but use a generic Transformer_ is valid. How do you solve the illustrated problem in your (multilanguage) applications? I guess you also have the problem that you need to edit a text in multiple languages.

Cheers

**Comment by johannesschobel** [comment]
This message proposes a possible solution for the illustrated "problem":

Lets do the following things:
1) Introduce a new `config` attribute `allow_get_all_languages = true/false` ( default `false` to keep backward-compatibility) that indicates if all `languages` shall be retrievable by the user. If so, the user may use the `app.locale = '*'` in order to indicate that he would like to get **all** languages (i.e., the array of translations).
2) In the `getTranslation(key, locale)` function return the array instead of the value if the locale is `*`.

I would be willing to make a PR with tests if you agree with this approach! I would really appreciate it because i really need this feature!

**Comment by freekmurze** [comment]
To me it makes no sense to add authorization functionality in a translations package. Do all of this in your own app by wrapping the functions provided by this package.

**Comment by johannesschobel** [comment]
again, this is **not** an authorization feature. This is just a "give me all languages" without explicitly calling the `$model->getTranslations('question')` function but rather calling `$model->question`.

This will reduce complexity and avoid code duplication. Furthermore, the proposed approach in my comment above is "backward compatible" and will not affect already running applications..

**Comment by freekmurze** [comment]
So, you want a config file that changes the behaviour of 

```
$model->nameOfTranslatableField
```

so that it gives not the translation of the field for the app locale but for all locales?

Seems to me that most users don't need this functionality and you should do this in your own project.

If I still misunderstood it, PR this so I have some code to look at.

**Comment by johannesschobel** [comment]
yes, basically you are right..
I would like to have a custom _language_ (basically it is no language), called `*` (or whatever -> config file!) that allows to get all translations instead of one specific translation.

Consider this example:
A journalist needs to write an article in different languages. In his UI he has a tabbed view - one tab for each language. And he needs to maintain the texts. Therefore, his application needs to request **all** translations - and not one specific.

Of course, the application could make `n` requests, but that would be stupid, as some data of a NewsArticle does not need to be translated (e.g., the `release_date` or `author_name`) and so on.. You would request and process data you already have.
Furthermore, you would need to have to rewrite `Transformer`s and so on, that results in code-duplication.

The problem is - I cannot do this in my own application, if I use your package, without having to rewrite most of my Transformers and logic. Furthermore, a _give me all translations_ feature would belong to this package and not my application ;) (I know that there is a `getTranslations()` method available - however, as mentioned before, this results in code-duplication!)

I can make a quick-and-dirty GIST at the evening if you like and explain it on code-level. If you are willing to accept a PR, I would like to contribute!

**Comment by freekmurze** [comment]
I'd love to see a gist, from I understand it now, it's still something that should be done in your app.

(Of course you have the option to fork this package and modify it to your own needs)

**Comment by johannesschobel** [comment]
Hey man, i just added a [GIST here](https://gist.github.com/johannesschobel/58ca53f19c365db7aef999ca6c2f07ae) to sum up my problem, illustrate my approach how to solve it and so on. 

I would appreciate if, if you have the time to give me feedback. I would be willing to contribute and make a PR according to your guidelines.

I would rather not fork this package as i would like to be "up to date" if you introduce other handy features 😄 

Cheers

**Comment by freekmurze** [comment]
After reading your gist I still think that these changes are not needed for the vast majority of the users of the package.

You can easily override the `getTranslation` function in your app and make it to whatever you want.

**Comment by johannesschobel** [comment]
"[...] not needed _for the vast majority_ of the users [...]". But still for some of them.
So you will not merge a PR, right?

**Comment by freekmurze** [comment]
Probably not.

**Comment by Bolhy10** [comment]
@johannesschobel 

How about @johannesschobel. I understand your point and it's what I'm looking for for the rest of the time I'm doing. You have an example or repository that you can share to see how you solved it. ? I would appreciate. Greetings.

**Comment by Bolhy10** [comment]
@johannesschobel 


Yes, what I have are several users, for example in the user application the user selects the language of their choice and the answers, as well as the names that were translated must appear in the selected language, I am including it as you send a header to bring me the language of the user, but what happens in the web administrator, the administrator must have the option to leave all the languages ​​because you must have the option to change it. I use the transformer but it brings me a single language if I want all the languages ​​so that the administrator changes them as I would? It gets tedious to repeat code. Greetings.

**Comment by Bolhy10** [comment]
@johannesschobel 


which is better to create a large scale api https://github.com/spatie/laravel-translatable or https://github.com/dimsav/laravel-translatable

**Comment by johannesschobel** [comment]
i worked with `dimsav/laravel-translatable` in another project.. it is a great package, BUT (and this may be a huge BUT, depending on your application scenario). `dimsav` stores its localizations in a respective `localization` table per model.

For example, if you have a `Team` model that should be localized (e.g., the `name` and `description` attributes), you will have a  `teams` and a `team_translations` table). The `team_translations` contains the `name` and `description`, the `teams` table the rest of your properties. Furthermore, there are 2 models (`Team` and `TeamTranslation`) linked via `Relationships` and so on.. However, via "magic", you can still access `$team->name` to get the translated name..

I think, both different approaches have their pro and cons.. However, from the "configuration / development" point-of-view, the `spatie` package may be easier-to-integrate / faster-to-use.. If you already have an application, that shall be "internationalized", i would probably go for the `spatie` package..

Maybe @freekmurze may give some additional information on the difference between `dimsav` and `spatie`? I once read an article, where the "design decisions" for this package were discussed.. maybe this helps you as well?!

Cheers

**Comment by Bolhy10** [comment]
Hi @freekmurze 
The api that I want to make is on a large scale, I wanted to know which one would help me the most. It's true what you say creating a table more for translations is a tedious thing.

And for example: As administrator I am responsible for entering both the **name and the description** in several languages ​​from the **web administrator** neither gives me that option to bring the entire translation so that the administrator can update those fields. I do not know if @freekmurze if you have an idea that can help me here, and not be creating more transformers for that. I would appreciate. 

@johannesschobel 

How did you solve this problem so as not to be creating redundant code?
 I would appreciate.
Greetings.
