### ISSUE TITLE
WhereIn?

### ISSUE THREAD

**Issue by CrixuAMG** [spatie/laravel-translatable#69]
In the README.md file is written that we can use `NewsItem::where('name->en', 'Name in English')->get();`.
I want to do this basically: `NewsItem::whereIn('name->en', ['test_1', 'test_2'])->get();`, however, this does not yield any results.
If I do `toSql()` and run the query with and without the `whereIn` section, I can see that without I get results as expected (though of course not filtered), but I get nothing when using the `whereIn` part of the query.
I also get an error stating: `Invalid JSON path expression. The error is around character position 1.`.
The data in the tables is valid JSON.

**Comment by sebastiandedeyne** [comment]
Hmm could be wrong this sounds more like an issue for laravel/framework...

**Comment by CrixuAMG** [comment]
@sebastiandedeyne I'll try asking there, and copy the answer to here so it can help others. Thanks for suggesting :)

**Comment by CrixuAMG** [comment]
User `themsaid` at `laravel/framework` shared the following:
"Yes it doesn't work with whereIn at the moment :)"

As soon as I know more I'll post it here, closing issue now.

**Comment by CrixuAMG** [comment]
If anyone is looking for the issue I created, here is the [link](https://github.com/laravel/framework/issues/20721)
