### ISSUE TITLE
Translate in paginated Json data

### ISSUE THREAD

**Issue by microdesign** [spatie/laravel-translatable#74]
I use your package with a backpack and try to make search field with AJAX to a model which has a name which is translatable - but when the API return results I see only JSON inside and not translations of the field.

So how I can have Laravel paginated results with already translated strings inside.

**Comment by freekmurze** [comment]
There's an example in the docs that explains how to add translations to json responses.

https://github.com/spatie/laravel-translatable#using-translations-in-json-responses

**Comment by microdesign** [comment]
Thanks for the help

**Comment by ankurk91** [comment]
I dont know why the example has been removed from readme

```php
// in your model

    /**
     * Convert the model instance to an array.
     *
     * @return array
     */
    public function toArray()
    {
        $attributes = parent::toArray();
        
        foreach ($this->getTranslatableAttributes() as $name) {
            $attributes[$name] = $this->getTranslation($name, app()->getLocale());
        }
        
        return $attributes;
    }
}
```
