### ISSUE TITLE
translation in seeds

### ISSUE THREAD

**Issue by microdesign** [spatie/laravel-translatable#78]
The traslations in seeders are encoded in wrong way and in tha database are inserted strings like 
this "{"bg":"\u041c\u0435\u043a\u0438 \u043a\u043e\u0440\u0438\u0446\u0438"}"
everything is OK when I insert from web pages.

**Comment by freekmurze** [comment]
How can this problem be reproduced?

**Comment by microdesign** [comment]
Just create new entry from the seed 

`
$type2 = BookType::create([
            'name' => 'Твърди корици',
        ]);
`

**Comment by freekmurze** [comment]
Do not use the `create` method to pass the translations, use `setTranslations` instead:

```php
$type = (BookType::create())->setTranslations('name', ['ru' => 'Твърди корици' ]);
```

**Comment by microdesign** [comment]
OK, then what is your suggestion when I use your lib with Backpack which recommends translations with your package?
