### ISSUE TITLE
Set flag to your json_encode

### ISSUE THREAD

**Issue by microdesign** [spatie/laravel-translatable#79]
I want to add flag to json_encode JSON_UNESCAPED_UNICODE because you store the Cyrillic information incorrectly. 

How can I make this?

**Comment by freekmurze** [comment]
You can override the `asJson` function on an Eloquent model like this:

```php
    /**
     * Encode the given value as JSON.
     *
     * @param  mixed  $value
     * @return string
     */
    protected function asJson($value)
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }
```

**Comment by microdesign** [comment]
Thanks - yes I already found this is the problem
