### ISSUE TITLE
Select many items in a specific language?

### ISSUE THREAD

**Issue by sdebacker** [spatie/laravel-translatable#8]
Hello Freek,

I recently played with this package, but I'm stuck with a problem:
How to select many items in only one language ?

I tried:

```php
->select('content->'.app()->getLocale().' AS content')
```

But I get quotes around the value.

Then I tried without luck to JSON_UNQUOTE:

```php
->select(DB::raw('JSON_UNQUOTE(content->'.app()->getLocale().')'))
```

For now I created a custom collection filter but it's far from ideal:

```php
Collection::macro('translate', function ($locale = null) {
    $locale = $locale ?: app()->getLocale();

    return $this->map(function ($item) use ($locale) {
        foreach ($item->getAttributes() as $key => $value) {
            if (in_array($key, $item->translatable)) {
                $item->$key = $item->translate($key, $locale);
            }
        }

        return $item;
    });
});
```

Any advice would be appreciated.
And thank you again for your great packages.

**Comment by freekmurze** [comment]
Hi Samuel,

did not have to do this myself.  You can only use the json functions in mysql version 5.7. Are you running that version?

**Comment by freekmurze** [comment]
Maybe `JSON_EXTRACT` can help you? 
https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-extract

**Comment by sdebacker** [comment]
Yes, I have the latest MySQL version. I now succeeded with JSON_QUOTE:

```php
->select(DB::raw("JSON_UNQUOTE(content->'$.".app()->getLocale()."') AS content"))
```

It should be great if Laravel could support this without the need of using DB::raw.

**Comment by sdebacker** [comment]
With MySQL 5.7.13 we have this shorthand for JSON_QUOTE : 

```
column->>path
```

https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-inline-path
