### ISSUE TITLE
Any mechanism to work with Slugs?

### ISSUE THREAD

**Issue by bloggervista** [spatie/laravel-translatable#81]
In your post in laravel news I liked the idea of articles. But we know article have various properties like slugs, title and content. This package makes easy to retrieve title and content according to locale. But there is one catch how can we make work with slug. 

How can we correctly display the post according to slug that also has been localized.?

Thanks for this awesome package :)

**Comment by freekmurze** [comment]
Here's an example on how you can search within the translations:

```php
Post::where('slug->en', 'slug-in-english')->first();
```

**Comment by Fredwared** [comment]
@freekmurze that method compatible with MySQL 5.7or above right? any trick exists with MySQL 5.1? Unfortunately most shared hostings still uses this version. Thanks.

**Comment by freekmurze** [comment]
I don’t use anything below 5.7 myself, so I don’t know...

**Comment by bloggervista** [comment]
We are fine with 5.7 because if we can upgrade to php7 we can upgrade mysql
to 5.7 and laravel is not made for shared hosting. And i think it is
compatibpe with sqlite and pgsql
