### ISSUE TITLE
Unique Translation validation rule

### ISSUE THREAD

**Issue by ivanvermeyen** [spatie/laravel-translatable#84]
Hello,

First of all, thanks for sharing all of your amazing packages with us!

I'm working on a validation rule that works like the `unique` rule that Laravel provides, except that it looks inside a JSON column with translations. This is intended to be used with your package, but there may be other use cases...?

https://github.com/codezero-be/laravel-unique-translation

Do you think such a validation rule could be useful for your package?

**Comment by freekmurze** [comment]
Thank you for the suggestion, but I'm going to leave it the way things are now.

For our projects the current code works ok and there are no users reporting issues around this.

**Comment by ctf0** [comment]
@freekmurze maybe add it as side note in the readme ?

**Comment by freekmurze** [comment]
@ctf0 sure, send a PR.

**Comment by ivanvermeyen** [comment]
Thanks for the mention in the readme, @freekmurze, @ctf0 ❤️
