### ISSUE TITLE
how to bypass the the package

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-translatable#86]
atm am trying to build a revision manager, so when restoring to an old revision, the package will put the new value under the current locale,

where instead i just want to replace the whole column value without any extra operations.

**Comment by freekmurze** [comment]
If you use the query builder to perform the update the package probably won't get in your way

https://laravel.com/docs/5.5/queries#updates

**Comment by ctf0** [comment]
actually i was searching for a way to reset `$translatable` prop programmatically.

**Comment by ctf0** [comment]
or maybe fire an event b4 saving which have an option to skip the translation.
