### ISSUE TITLE
Compatibility with Accessor/Mutator?

### ISSUE THREAD

**Issue by arakash92** [spatie/laravel-translatable#88]
the HasTranslations trait doesn't seem to be able to cope with translatable attributes who also have a mutator.

Given this Model:

```php
    class PortfolioItem extends Model
    {
        use HasTranslations;
    
        protected $table = 'portfolioitems';
    
        protected $fillable = ['category'];
    
        public $translatable = ['category'];
       
        public function setCategoryAttribute($category)
        {
            $this->attributes['category'] = strtolower($category);
        }
    }
```

And this statement:
```php
$model->category = 'category';
echo $model->category;
```

Gives:

```php
[
    'en' => null,
]
```

**Comment by ctf0** [comment]
i was going to ask the same question and i think the issue is related to `$this->attributes['category']` which is now invalid because u have sub items under it.

so probably the package should have a helper that check for mutators and apply it to each locale on save automatically.

**Comment by freekmurze** [comment]
Feel free to submit a fully tested backwards compatible PR that fixes this.

**Comment by maxim-dev** [comment]
let see to /src/HasTranslations.php:109

I suppose instead of this
```
        if ($this->hasSetMutator($key)) {
            $method = 'set'.Str::studly($key).'Attribute';
            $value = $this->{$method}($value);
        }
```

It should be like this
```
        if ($this->hasSetMutator($key)) {
            $method = 'set'.Str::studly($key).'Attribute';
            $this->{$method}($value);
            $value = $this->attributes[Str::snake($key)];
        }
```
It's works for me as expected.


So, @arakash92 please consider to return value from your mutator as a hotfix.
Like this:

```
        public function setCategoryAttribute($category)
        {
            $this->attributes['category'] = strtolower($category);
            return $this->attributes['category'];
        }
```
But imho it is not good, because mutator always should return `$this` to stay able to implement "fluent" interface. Please see `setAttribute()` method from `HasAttribute` trait
`/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:517`

**Comment by alexjoffroy** [comment]
Hi guys, the hotfix from @maxim-dev is working well, but as he said it would be better to keep returning `$this`. Is there someone working on a PR ? Is there something I can do ?

**Comment by freekmurze** [comment]
Sure, send a PR with tests.
