### ISSUE TITLE
[Feature proposal] When fallback isn't available, but others languages are...

### ISSUE THREAD

**Issue by mathieutu** [spatie/laravel-translatable#90]
Hi guys!
I'm currently handling something that it could be interesting to add to the core.
If the current locale isn't available, and the fallback one neither (easy if the current is the fallback), the string will be empty, even if there are some translations in the field.

My example:
I'm building a form to fill a menu of products. Products are translatable and the user can choose the language with a selector. Basic.

If I create a product when English (fallback) is selected, when changing to French, my product will have all english translations, and it's ok.

If I create a product when French is selected, when changing to English, my product will have all attributes empty... and it's not ok!

2 solutions, in `\Spatie\Translatable\HasTranslations::normalizeLocale`: 

- Set an array of fallback in config, and return the first fallback available.
- Fallback to the first language available, if the fallback isn't available.

Imo, both should be combined. 
It can be configurable, to preserve the actual behaviour.

What do you think?

**Comment by mathieutu** [comment]
My _quick and dirty_ version, base on the second solution: 
```php
$fallbackLocale = config('translatable.fallback_locale');
if ($fallbackLocale !== null && in_array($fallbackLocale, $this->getTranslatedLocales($key))) {
    return $fallbackLocale;
}
return $this->getTranslatedLocales($key)[0] ?? $locale;
```

**Comment by freekmurze** [comment]
Instead of hard coding the behaviour I'd add a `useFallBackLocale` to the `HasTranslations` trait. If there translation for the current locale, the return value of that function could get use.

In that way users can add any behaviour they want.

Thoughts?

**Comment by mathieutu** [comment]
Yeah, why not?
If I've understood you just want to migrate the actual code for fallback to a `useFallBackLocale` method, which can be overwritten by the developer ? It would allow to overwrite just this method instead the entire `normalizeLocale` (what I've down on my side)

**Comment by ctf0** [comment]
not sure this is what u r looking for but i have this
```php
public function getAttributeValue($key)
    {
        if (!$this->isTranslatableAttribute($key)) {
            return parent::getAttributeValue($key);
        }

        return $this->getTranslationWithoutFallback($key, app()->getLocale());
    }
```

**Comment by ctf0** [comment]
@mathieutu i think what u want is to show the title whether its available in current locale or not "empty" ex.
```js
{
"en" : 'my product',
"fr" : null
}
```

i have this in view
```blade
@if (in_array(app()->getLocale(), $post->getTranslatedLocales('title')))
    <a href="{{ $post->url }}">{{ $post->title }}</a>
@else
    <span>{{ empty($post->title) ? collect($post->getTranslations('title'))->first() : $post->title }}</span>
@endif
```

so this basically show an anchor if the title is avail in current active local, or fall back to whatever is avail in the db.

if u dont care about the anchor, just use the span **"like having an edit page title for a modal that is not avail in current local"**

this is also achievable in js but the title have to be
```js
title: {
fr:"bla"
en:"bla bla"
}
```
```js
getTitle(title) {
    let locale = this.locale
    let v = Object.keys(title).indexOf(locale)

    return title.hasOwnProperty(locale) ? Object.values(title)[v] : Object.values(title)[0].concat(` "${Object.keys(title)[0]}"`)
},
```

**Comment by mathieutu** [comment]
Hi @ctf0.
I'm sorry but I didn't understand your point. 
This issue is not a question about a problem, it's a feature proposal.

I just think @freekmurze forgot that (as I did before your comment 😅)

**Comment by ctf0** [comment]
oh okay, my bad 👍 .

however if this is going to be added i think it might be a good idea to enable/disable it by an option instead of forcing it on the user as the expected behavior is not to show something if its not avail in the active locale.
