### ISSUE TITLE
Return value must be of the type array, null returned

### ISSUE THREAD

**Issue by sasokovacic** [spatie/laravel-translatable#92]
Hi, 

how can one translate existing model records? 
I have a table job_categories with columns id and name...
This table is already populated with categories. The name column contains plain text...
When I set JobCategory model to be translatable and try to translate the name field I get this error

> error: Return value of App\JobCategory::getTranslations() must be of the type array, null returned..

Do I get this error because the name field still contains plain text? Should I first  translate everything to a new field and then copy everything back to original?

**Comment by freekmurze** [comment]
This package does not contain any logic to work with plain text in the translated columns.

You should first convert the data in the translatable columns to json.
