### ISSUE TITLE
Inserting & Updating Related Models is not work

### ISSUE THREAD

**Issue by soeurngsar** [spatie/laravel-translatable#94]
Sorry for this open issue, I saw in Laravel documentation that we can save related model by call the relation like bellow, but when I do this the related model field is not translate and save raw data to database so it
not the valid json format.

Look at the example:
`$comment = new App\Comment(['message' => 'A new comment.']);

$post = App\Post::find(1);

$post->comments()->save($comment);`

if I call $comment->save(); it work correctlly, but when I call $post->comments()->save($comment); it not work.

Thank for you help.

**Comment by freekmurze** [comment]
This question is not related to this package, but to Laravel. Use a forum like https://laracasts.com/forum or https://laravel.io for general Laravel questions.

**Comment by soeurngsar** [comment]
Sorry , maybe my question is not clear. what I want to ask you is not the Laravel problem; I mean when we create or update directly to model by calling static method for example User::create([]) or other methos like this this package will convert translatable fields to json correctlly, but if we call create or update using relationship like $user->profile()->create([]) the this package is not convert data to json and it save original data to the database. I think this is because this package it not handle correctly on relationship eager loading or something.
