### ISSUE TITLE
Decrease and speed up the response

### ISSUE THREAD

**Issue by brokerUA** [spatie/laravel-translatable#95]
Are there any ideas for implementing such improvements?

- [ ] Get the translation, not full json-object.
- [ ] Use the stored generated column with index for accelerate search.

The implementation through SELECT:
```
public static function __callStatic($method, $parameters)
{

    if ($method == 'select') {

        $instance = new static;

        $parameters = array_map(function($key) use ($instance) {
                if (isset($instance->translatable) && in_array($key, $instance->translatable)) {
                    return $key . '__' . config('app.locale') . ' as ' . $key;
                }

                return $key;
            }, $parameters);

        return $instance->$method(...$parameters);
    }

    return parent::__callStatic($method, $parameters);
}
```
Migration:
```
...
$table->string('name__en')->virtualAs("`name` ->> '$.en'");
$table->string('name__ua')->virtualAs("`name` ->> '$.ua'");

//add index where need, because will take memory in DB
$table->index('name__en'); 
$table->index('name__ua');
...
```
Example:
```
$book = Book::select('name')->first();
$book->name; //name by current lacale
```

**Comment by sebastiandedeyne** [comment]
If you're using a recent MySQL version, this shouldn't be an issue, no?

https://github.com/spatie/laravel-translatable#querying-translatable-attributes

**Comment by brokerUA** [comment]
But it will be without index because JSON columns cannot be indexed directly. 
https://dev.mysql.com/doc/refman/5.7/en/create-table-secondary-indexes.html#json-column-indirect-index

`NewsItem::where('name->en', 'Name in English')->get();`
And there are need to set local name directly. My proposal through rewrite `__callStatic` (select, where, etc.) method.

Maybe there is another, more correct way?

**Comment by freekmurze** [comment]
I'd like to keep this package very simple. Do you have any benchmarks for the performance improvements?

**Comment by brokerUA** [comment]
Only based on known facts that the indexed field is processed faster and it is better to get less data than more (one translation, instead of all).

Thanks for comments, if I bring my solution to the working version, I will inform.
